# BTC

### BiasFinder

In [1]:
import pandas as pd
import numpy as np
import math
import time

In [2]:
base_dir = "../../data/biasfinder_deadline/occupation/"
df = pd.read_csv(base_dir + "test.csv", header=None, sep="\t", names=["label", "mutant", "mtnt", "template", "original", "occupation"])
df

,label,mutant,mtnt,template,original,occupation
0,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,attendant
1,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,cashier
2,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,teacher
3,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,nurse
4,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,assistant
...,...,...,...,...,...,...
3629,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",nutritionist
3630,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",photographer
3631,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",police officer
3632,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",singer
3633,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",undertaker

In [5]:
def read_txt(fpath):
    pred = []
    file = open(fpath)
    lines = file.readlines()
    for l in lines :
        pred.append(int(l))
    file.close()
    
    return pred

In [6]:
output_dir = "biasfinder_deadline/occupation"

result_dir = "../../result/" + output_dir + "/"

path = result_dir + "results_data.txt"

pred = read_txt(path)

print(len(pred))

3634

In [7]:
df["prediction"] = pred

In [8]:
df

,label,mutant,mtnt,template,original,occupation,prediction
0,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,attendant,0
1,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,cashier,0
2,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,teacher,0
3,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,nurse,0
4,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,assistant,0
...,...,...,...,...,...,...,...
3629,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",nutritionist,1
3630,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",photographer,1
3631,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",police officer,1
3632,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",singer,1
3633,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",undertaker,1

### Use Groupby to Group the text by Template

In [9]:
df["template"] = df["template"].astype("category")
df["template_id"] = df["template"].cat.codes

In [10]:
gb = df.groupby("template_id")

In [11]:
gb.count()

             label  mutant  mtnt  template  original  occupation  prediction
template_id
0               79      79    79        79        79          79          79
1               79      79    79        79        79          79          79
2               79      79    79        79        79          79          79
3               79      79    79        79        79          79          79
4               79      79    79        79        79          79          79
5               79      79    79        79        79          79          79
6               79      79    79        79        79          79          79
7               79      79    79        79        79          79          79
8               79      79    79        79        79          79          79
9               79      79    79        79        79          79          79
10              79      79    79        79        79          79          79
11              79      79    79        79        79          79          79
12              79      79    79        79        79          79          79
13              79      79    79        79        79          79          79
14              79      79    79        79        79          79          79
15              79      79    79        79        79          79          79
16              79      79    79        79        79          79          79
17              79      79    79        79        79          79          79
18              79      79    79        79        79          79          79
19              79      79    79        79        79          79          79
20              79      79    79        79        79          79          79
21              79      79    79        79        79          79          79
22              79      79    79        79        79          79          79
23              79      79    79        79        79          79          79
24              79      79    79        79        79          79          79
25              79      79    79        79        79          79          79
26              79      79    79        79        79          79          79
27              79      79    79        79        79          79          79
28              79      79    79        79        79          79          79
29              79      79    79        79        79          79          79
30              79      79    79        79        79          79          79
31              79      79    79        79        79          79          79
32              79      79    79        79        79          79          79
33              79      79    79        79        79          79          79
34              79      79    79        79        79          79          79
35              79      79    79        79        79          79          79
36              79      79    79        79        79          79          79
37              79      79    79        79        79          79          79
38              79      79    79        79        79          79          79
39              79      79    79        79        79          79          79
40              79      79    79        79        79          79          79
41              79      79    79        79        79          79          79
42              79      79    79        79        79          79          79
43              79      79    79        79        79          79          79
44              79      79    79        79        79          79          79
45              79      79    79        79        79          79          79

In [12]:
len(gb.size())

46

In [13]:
df

,label,mutant,mtnt,template,original,occupation,prediction,template_id
0,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,attendant,0,45
1,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,cashier,0,45
2,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,teacher,0,45
3,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,nurse,0,45
4,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,assistant,0,45
...,...,...,...,...,...,...,...,...
3629,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",nutritionist,1,2
3630,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",photographer,1,2
3631,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",police officer,1,2
3632,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",singer,1,2
3633,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",undertaker,1,2

In [16]:
# id = 376068
# df.iloc[id]["mutant"]

In [18]:
# df.iloc[id]["original"]

In [19]:
# df.iloc[id]["template"]

### Get DF template only

In [20]:
df

,label,mutant,mtnt,template,original,occupation,prediction,template_id
0,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,attendant,0,45
1,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,cashier,0,45
2,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,teacher,0,45
3,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,nurse,0,45
4,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,assistant,0,45
...,...,...,...,...,...,...,...,...
3629,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",nutritionist,1,2
3630,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",photographer,1,2
3631,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",police officer,1,2
3632,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",singer,1,2
3633,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",undertaker,1,2

In [21]:
dft = df.iloc[:,[0,3,4, -1]]
dft = dft.drop_duplicates().reset_index(drop=True)
dft

,label,template,original,template_id
0,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,45
1,1,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,28
2,0,"b "" ' A New Generation ' is the third Amityvil...","b "" ' A New Generation ' is the third Amityvil...",0
3,1,"b ' For those of you still in the dark, I will...","b ' For those of you still in the dark, I will...",25
4,0,b ' Even my five year old was bored. Very pred...,b ' Even my five year old was bored. Very pred...,23
5,1,"b "" There are 3 of these movies, all similarly...","b "" There are 3 of these movies, all similarly...",11
6,0,b ' If this film were to be rated on a scale o...,b ' If this film were to be rated on a scale o...,34
7,0,b ' French Cinema sucks! Down with all these p...,b ' French Cinema sucks! Down with all these p...,26
8,0,b ' Attractive husband and wife writing team R...,b ' Attractive husband and wife writing team R...,20
9,0,b ' I remember watching this movie on TV a few...,b ' I remember watching this movie on TV a few...,32
10,1,"b ' Billy Crystal is Larry, @DetAAN @OCCUPATIO...","b ' Billy Crystal is Larry, a writer who hasn'...",21
11,0,b ' The biggest problem with this film is that...,b ' The biggest problem with this film is that...,42
12,0,"b ' Here's example number 87,358 of Hollywood'...","b ' Here's example number 87,358 of Hollywood'...",29
13,0,b ' A comedy that spoofs the inspirational spo...,b ' A comedy that spoofs the inspirational spo...,18
14,1,"b "" First off let me say that this is probably...","b "" First off let me say that this is probably...",4
15,0,b ' Perhaps the wildest outlier in Alfred Hitc...,b ' Perhaps the wildest outlier in Alfred Hitc...,39
16,0,"b ' I happened to catch this on TV, and wanted...","b ' I happened to catch this on TV, and wanted...",31
17,1,"b "" One day a red alley cat is fed up of being...","b "" One day a red alley cat is fed up of being...",9
18,0,"b ' Brainy, cross - dressing little boy finds ...","b ' Brainy, cross - dressing little boy finds ...",22
19,1,"b ' KRAMER VS KRAMER won five Oscars, includin...","b ' KRAMER VS KRAMER won five Oscars, includin...",36
20,0,"b "" wow, i just got one watching this. How CRA...","b "" wow, i just got one watching this. How CRA...",17
21,0,"b "" This movie is one of the worse movies of a...","b "" This movie is one of the worse movies of a...",12
22,0,"b "" The Patriot (nothing to do with the Mel Gi...","b "" The Patriot ( nothing to do with the Mel G...",10
23,1,"b ' Hey all you jive hustlers, you stone foxes...","b ' Hey all you jive hustlers, you stone foxes...",30
24,1,"b "" This movie was beautiful and touching. It ...","b "" This movie was beautiful and touching. It ...",14
25,0,"b "" This movie was a major bait and switch. I ...","b "" This movie was a major bait and switch. I ...",13
26,0,b ' Jackie Chan movies are typical examples of...,b ' Jackie Chan movies are typical examples of...,35
27,1,b ' I tivo'd this on Turner Classic just becau...,b ' I tivo'd this on Turner Classic just becau...,33
28,0,"b "" I bought the DVD out of a big bin for$ 4.9...","b "" I bought the DVD out of a big bin for$ 4.9...",5
29,0,"b "" Kevin Spacey is my favorite @OCCUPATION of...","b "" Kevin Spacey is my favorite actor of all t...",8
30,1,"b "" I'm pleased that this was the work of fore...","b "" I'm pleased that this was the work of fore...",7
31,0,"b ' Like many, this dung heap caught my eye wh...","b ' Like many, this dung heap caught my eye wh...",37
32,1,b ' A dangerous psychopathic killer Jacob Good...,b ' A dangerous psychopathic killer Jacob Good...,19
33,0,"b "" I only comment on really very good films a...","b "" I only comment on really very good films a...",6
34,1,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1
35,0,b ' What about Scream Baby Scream is supposed ...,b ' What about Scream Baby Scream is supposed ...,44
36,1,b ' This film is great with some of the best s...,b ' This film is great with some of the best s...,43
37,0,b ' The actors are so bland that it's almost i...,b ' The actors are so bland that it's almost i...,41
38,1,"b ' Ponyo, written and directed by Hayao Miyaz...","b ' Ponyo, written and directed by Hayao Miyaz...",40
39,1,"b ' My favorite show of all time! Yeah, I thou...","b ' My favorite show of all time! Yeah, I thou...",38
40,1,b ' German - born Turkish @OCCUPATION Faith Ak...,b ' German - born Turkish director Faith Akin ...,27
41,1,b ' Every review I have read so far seems to h...,b ' Every review I have read so far seems to h...,24
42,1,"b "" When it was released, in the beginning of ...","b "" When it was released, in the beginning of ...",16
43,1,"b "" This was really one of the most enjoyable ...","b "" This was really one of the most enjoyable ...",15
44,1,"b "" First of all, ignore the comment about how...","b "" First of all, ignore the comment about how...",3
45,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",2

In [22]:
# dft.to_csv("occupation_template.csv")

In [186]:
# df.iloc[dft.index].to_csv("cari-contoh-occupation.csv")

In [23]:
## template
dft = dft.sort_values(by=["template_id"])
dft = dft.reset_index(drop=True)

## mutant
df = df.reset_index(drop=True)

In [24]:
df

,label,mutant,mtnt,template,original,occupation,prediction,template_id
0,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,attendant,0,45
1,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,cashier,0,45
2,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,teacher,0,45
3,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,nurse,0,45
4,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,assistant,0,45
...,...,...,...,...,...,...,...,...
3629,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",nutritionist,1,2
3630,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",photographer,1,2
3631,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",police officer,1,2
3632,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",singer,1,2
3633,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",undertaker,1,2

In [25]:
dft

,label,template,original,template_id
0,0,"b "" ' A New Generation ' is the third Amityvil...","b "" ' A New Generation ' is the third Amityvil...",0
1,1,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1
2,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",2
3,1,"b "" First of all, ignore the comment about how...","b "" First of all, ignore the comment about how...",3
4,1,"b "" First off let me say that this is probably...","b "" First off let me say that this is probably...",4
5,0,"b "" I bought the DVD out of a big bin for$ 4.9...","b "" I bought the DVD out of a big bin for$ 4.9...",5
6,0,"b "" I only comment on really very good films a...","b "" I only comment on really very good films a...",6
7,1,"b "" I'm pleased that this was the work of fore...","b "" I'm pleased that this was the work of fore...",7
8,0,"b "" Kevin Spacey is my favorite @OCCUPATION of...","b "" Kevin Spacey is my favorite actor of all t...",8
9,1,"b "" One day a red alley cat is fed up of being...","b "" One day a red alley cat is fed up of being...",9
10,0,"b "" The Patriot (nothing to do with the Mel Gi...","b "" The Patriot ( nothing to do with the Mel G...",10
11,1,"b "" There are 3 of these movies, all similarly...","b "" There are 3 of these movies, all similarly...",11
12,0,"b "" This movie is one of the worse movies of a...","b "" This movie is one of the worse movies of a...",12
13,0,"b "" This movie was a major bait and switch. I ...","b "" This movie was a major bait and switch. I ...",13
14,1,"b "" This movie was beautiful and touching. It ...","b "" This movie was beautiful and touching. It ...",14
15,1,"b "" This was really one of the most enjoyable ...","b "" This was really one of the most enjoyable ...",15
16,1,"b "" When it was released, in the beginning of ...","b "" When it was released, in the beginning of ...",16
17,0,"b "" wow, i just got one watching this. How CRA...","b "" wow, i just got one watching this. How CRA...",17
18,0,b ' A comedy that spoofs the inspirational spo...,b ' A comedy that spoofs the inspirational spo...,18
19,1,b ' A dangerous psychopathic killer Jacob Good...,b ' A dangerous psychopathic killer Jacob Good...,19
20,0,b ' Attractive husband and wife writing team R...,b ' Attractive husband and wife writing team R...,20
21,1,"b ' Billy Crystal is Larry, @DetAAN @OCCUPATIO...","b ' Billy Crystal is Larry, a writer who hasn'...",21
22,0,"b ' Brainy, cross - dressing little boy finds ...","b ' Brainy, cross - dressing little boy finds ...",22
23,0,b ' Even my five year old was bored. Very pred...,b ' Even my five year old was bored. Very pred...,23
24,1,b ' Every review I have read so far seems to h...,b ' Every review I have read so far seems to h...,24
25,1,"b ' For those of you still in the dark, I will...","b ' For those of you still in the dark, I will...",25
26,0,b ' French Cinema sucks! Down with all these p...,b ' French Cinema sucks! Down with all these p...,26
27,1,b ' German - born Turkish @OCCUPATION Faith Ak...,b ' German - born Turkish director Faith Akin ...,27
28,1,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,28
29,0,"b ' Here's example number 87,358 of Hollywood'...","b ' Here's example number 87,358 of Hollywood'...",29
30,1,"b ' Hey all you jive hustlers, you stone foxes...","b ' Hey all you jive hustlers, you stone foxes...",30
31,0,"b ' I happened to catch this on TV, and wanted...","b ' I happened to catch this on TV, and wanted...",31
32,0,b ' I remember watching this movie on TV a few...,b ' I remember watching this movie on TV a few...,32
33,1,b ' I tivo'd this on Turner Classic just becau...,b ' I tivo'd this on Turner Classic just becau...,33
34,0,b ' If this film were to be rated on a scale o...,b ' If this film were to be rated on a scale o...,34
35,0,b ' Jackie Chan movies are typical examples of...,b ' Jackie Chan movies are typical examples of...,35
36,1,"b ' KRAMER VS KRAMER won five Oscars, includin...","b ' KRAMER VS KRAMER won five Oscars, includin...",36
37,0,"b ' Like many, this dung heap caught my eye wh...","b ' Like many, this dung heap caught my eye wh...",37
38,1,"b ' My favorite show of all time! Yeah, I thou...","b ' My favorite show of all time! Yeah, I thou...",38
39,0,b ' Perhaps the wildest outlier in Alfred Hitc...,b ' Perhaps the wildest outlier in Alfred Hitc...,39
40,1,"b ' Ponyo, written and directed by Hayao Miyaz...","b ' Ponyo, written and directed by Hayao Miyaz...",40
41,0,b ' The actors are so bland that it's almost i...,b ' The actors are so bland that it's almost i...,41
42,0,b ' The biggest problem with this film is that...,b ' The biggest problem with this film is that...,42
43,1,b ' This film is great with some of the best s...,b ' This film is great with some of the best s...,43
44,0,b ' What about Scream Baby Scream is supposed ...,b ' What about Scream Baby Scream is supposed ...,44
45,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,45

## Get Number of Discordant Pairs for Each Template

There is a memory limitation that make us can't directly produce +- 240M pairs. Fortunately, the number of discordant pairs for each template can be calculate theoritically without crossing th data to get +- 240M pairs. This will solve the memory issue.

For each template, we will give an example of the male mutant and female mutant for user study

In [26]:
gb = df.groupby("template_id")
gb.count()

             label  mutant  mtnt  template  original  occupation  prediction
template_id
0               79      79    79        79        79          79          79
1               79      79    79        79        79          79          79
2               79      79    79        79        79          79          79
3               79      79    79        79        79          79          79
4               79      79    79        79        79          79          79
5               79      79    79        79        79          79          79
6               79      79    79        79        79          79          79
7               79      79    79        79        79          79          79
8               79      79    79        79        79          79          79
9               79      79    79        79        79          79          79
10              79      79    79        79        79          79          79
11              79      79    79        79        79          79          79
12              79      79    79        79        79          79          79
13              79      79    79        79        79          79          79
14              79      79    79        79        79          79          79
15              79      79    79        79        79          79          79
16              79      79    79        79        79          79          79
17              79      79    79        79        79          79          79
18              79      79    79        79        79          79          79
19              79      79    79        79        79          79          79
20              79      79    79        79        79          79          79
21              79      79    79        79        79          79          79
22              79      79    79        79        79          79          79
23              79      79    79        79        79          79          79
24              79      79    79        79        79          79          79
25              79      79    79        79        79          79          79
26              79      79    79        79        79          79          79
27              79      79    79        79        79          79          79
28              79      79    79        79        79          79          79
29              79      79    79        79        79          79          79
30              79      79    79        79        79          79          79
31              79      79    79        79        79          79          79
32              79      79    79        79        79          79          79
33              79      79    79        79        79          79          79
34              79      79    79        79        79          79          79
35              79      79    79        79        79          79          79
36              79      79    79        79        79          79          79
37              79      79    79        79        79          79          79
38              79      79    79        79        79          79          79
39              79      79    79        79        79          79          79
40              79      79    79        79        79          79          79
41              79      79    79        79        79          79          79
42              79      79    79        79        79          79          79
43              79      79    79        79        79          79          79
44              79      79    79        79        79          79          79
45              79      79    79        79        79          79          79

### Data crossing

In [27]:
import time

start = time.time()

identifier = "occupation"

mutant_example = []
mutant_prediction_stat = []
key = []
for i in range(len(gb.size())) :
# for i in range(10) :
    data = gb.get_group(i)
    dc = data.groupby(identifier)
    me = {} # mutant example
    mp = {} # mutant prediction
    key = []
    for k, v in dict(iter(dc)).items() :
        key.append(k)
        is_first_instance = True
        pos_counter = 0 # positive counter
        neg_counter = 0 # negative counter
        for m, p in zip(v["mutant"].values, v["prediction"].values) :
            if is_first_instance :
                me[k] = m
                is_first_instance = False
            if int(p) == 1 :
                pos_counter += 1
            else :
                neg_counter += 1
        mp[k] = {"pos": pos_counter, "neg" : neg_counter}
        
    mutant_example.append(me)
    mutant_prediction_stat.append(mp)
                            
end = time.time()
print("Execution time: ", end-start)

Execution time:  1.0064573287963867

In [28]:
print(len(mutant_example))
print(len(mutant_prediction_stat))

46
46

In [29]:
dft["mutant_example"] = mutant_example
dft["mutant_prediction_stat"] = mutant_prediction_stat
dft

,label,template,original,template_id,mutant_example,mutant_prediction_stat
0,0,"b "" ' A New Generation ' is the third Amityvil...","b "" ' A New Generation ' is the third Amityvil...",0,"{'CEO': 'b "" ' A New Generation ' is the third...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
1,1,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1,"{'CEO': 'b "" At first I thought this film was ...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
2,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",2,"{'CEO': 'b "" Compared to the acclaimed Hollywo...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
3,1,"b "" First of all, ignore the comment about how...","b "" First of all, ignore the comment about how...",3,"{'CEO': 'b "" First of all, ignore the comment ...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
4,1,"b "" First off let me say that this is probably...","b "" First off let me say that this is probably...",4,"{'CEO': 'b "" First off let me say that this is...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
5,0,"b "" I bought the DVD out of a big bin for$ 4.9...","b "" I bought the DVD out of a big bin for$ 4.9...",5,"{'CEO': 'b "" I bought the DVD out of a big bin...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
6,0,"b "" I only comment on really very good films a...","b "" I only comment on really very good films a...",6,"{'CEO': 'b "" I only comment on really very goo...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
7,1,"b "" I'm pleased that this was the work of fore...","b "" I'm pleased that this was the work of fore...",7,"{'CEO': 'b "" I'm pleased that this was the wor...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
8,0,"b "" Kevin Spacey is my favorite @OCCUPATION of...","b "" Kevin Spacey is my favorite actor of all t...",8,"{'CEO': 'b "" Kevin Spacey is my favorite CEO o...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
9,1,"b "" One day a red alley cat is fed up of being...","b "" One day a red alley cat is fed up of being...",9,"{'CEO': 'b "" One day a red alley cat is fed up...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
10,0,"b "" The Patriot (nothing to do with the Mel Gi...","b "" The Patriot ( nothing to do with the Mel G...",10,"{'CEO': 'b "" The Patriot (nothing to do with t...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
11,1,"b "" There are 3 of these movies, all similarly...","b "" There are 3 of these movies, all similarly...",11,"{'CEO': 'b "" There are 3 of these movies, all ...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
12,0,"b "" This movie is one of the worse movies of a...","b "" This movie is one of the worse movies of a...",12,"{'CEO': 'b "" This movie is one of the worse mo...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
13,0,"b "" This movie was a major bait and switch. I ...","b "" This movie was a major bait and switch. I ...",13,"{'CEO': 'b "" This movie was a major bait and s...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
14,1,"b "" This movie was beautiful and touching. It ...","b "" This movie was beautiful and touching. It ...",14,"{'CEO': 'b "" This movie was beautiful and touc...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
15,1,"b "" This was really one of the most enjoyable ...","b "" This was really one of the most enjoyable ...",15,"{'CEO': 'b "" This was really one of the most e...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
16,1,"b "" When it was released, in the beginning of ...","b "" When it was released, in the beginning of ...",16,"{'CEO': 'b "" When it was released, in the begi...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
17,0,"b "" wow, i just got one watching this. How CRA...","b "" wow, i just got one watching this. How CRA...",17,"{'CEO': 'b "" wow, i just got one watching this...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
18,0,b ' A comedy that spoofs the inspirational spo...,b ' A comedy that spoofs the inspirational spo...,18,{'CEO': 'b ' A comedy that spoofs the inspirat...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
19,1,b ' A dangerous psychopathic killer Jacob Good...,b ' A dangerous psychopathic killer Jacob Good...,19,{'CEO': 'b ' A dangerous psychopathic killer J...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
20,0,b ' Attractive husband and wife writing team R...,b ' Attractive husband and wife writing team R...,20,{'CEO': 'b ' Attractive husband and wife writi...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
21,1,"b ' Billy Crystal is Larry, @DetAAN @OCCUPATIO...","b ' Billy Crystal is Larry, a writer who hasn'...",21,"{'CEO': 'b ' Billy Crystal is Larry, a CEO who...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
22,0,"b ' Brainy, cross - dressing little boy finds ...","b ' Brainy, cross - dressing little boy finds ...",22,"{'CEO': 'b ' Brainy, cross - dressing little b...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
23,0,b ' Even my five year old was bored. Very pred...,b ' Even my five year old was bored. Very pred...,23,{'CEO': 'b ' Even my five year old was bored. ...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
24,1,b ' Every review I have read so far seems to h...,b ' Every review I have read so far seems to h...,24,{'CEO': 'b ' Every review I have read so far s...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
25,1,"b ' For those of you still in the dark, I will...","b ' For those of you still in the dark, I will...",25,{'CEO': 'b ' For those of you still in the dar...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
26,0,b ' French Cinema sucks! Down with all these p...,b ' French Cinema sucks! Down with all these p...,26,{'CEO': 'b ' French Cinema sucks! Down with al...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
27,1,b ' German - born Turkish @OCCUPATION Faith Ak...,b ' German - born Turkish director Faith Akin ...,27,{'CEO': 'b ' German - born Turkish CEO Faith A...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
28,1,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,28,{'CEO': 'b ' Great underrated movie great acti...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
29,0,"b ' Here's example number 87,358 of Hollywood'...","b ' Here's example number 87,358 of Hollywood'...",29,"{'CEO': 'b ' Here's example number 87,358 of H...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
30,1,"b ' Hey all you jive hustlers, you stone foxes...","b ' Hey all you jive hustlers, you stone foxes...",30,"{'CEO': 'b ' Hey all you jive hustlers, you st...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
31,0,"b ' I happened to catch this on TV, and wanted...","b ' I happened to catch this on TV, and wanted...",31,"{'CEO': 'b ' I happened to catch this on TV, a...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
32,0,b ' I remember watching this movie on TV a few...,b ' I remember watching this movie on TV a few...,32,{'CEO': 'b ' I remember watching this movie on...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
33,1,b ' I tivo'd this on Turner Classic just becau...,b ' I tivo'd this on Turner Classic just becau...,33,{'CEO': 'b ' I tivo'd this on Turner Classic j...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
34,0,b ' If this film were to be rated on a scale o...,b ' If this film were to be rated on a scale o...,34,{'CEO': 'b ' If this film were to be rated on ...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
35,0,b ' Jackie Chan movies are typical examples of...,b ' Jackie Chan movies are typical examples of...,35,{'CEO': 'b ' Jackie Chan movies are typical ex...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
36,1,"b ' KRAMER VS KRAMER won five Oscars, includin...","b ' KRAMER VS KRAMER won five Oscars, includin...",36,"{'CEO': 'b ' KRAMER VS KRAMER won five Oscars,...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
37,0,"b ' Like many, this dung heap caught my eye wh...","b ' Like many, this dung heap caught my eye wh...",37,"{'CEO': 'b ' Like many, this dung heap caught ...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
38,1,"b ' My favorite show of all time! Yeah, I thou...","b ' My favorite show of all time! Yeah, I thou...",38,{'CEO': 'b ' My favorite show of all time! Yea...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
39,0,b ' Perhaps the wildest outlier in Alfred Hitc...,b ' Perhaps the wildest outlier in Alfred Hitc...,39,{'CEO': 'b ' Perhaps the wildest outlier in Al...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
40,1,"b ' Ponyo, written and directed by Hayao Miyaz...","b ' Ponyo, written and directed by Hayao Miyaz...",40,"{'CEO': 'b ' Ponyo, written and directed by Ha...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
41,0,b ' The actors are so bland that it's almost i...,b ' The actors are so bland that it's almost i...,41,{'CEO': 'b ' The actors are so bland that it's...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
42,0,b ' The biggest problem with this film is that...,b ' The biggest problem with this film is that...,42,{'CEO': 'b ' The biggest problem with this fil...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
43,1,b ' This film is great with some of the best s...,b ' This film is great with some of the best s...,43,{'CEO': 'b ' This film is great with some of t...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'..."
44,0,b ' What about Scream Baby Scream is supposed ...,b ' What about Scream Baby Scream is supposed ...,44,{'CEO': 'b ' What about Scream Baby Scream is ...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."
45,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,45,{'CEO': 'b ' What symbolism! exclaimed a woman...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'..."

In [30]:
key

['CEO',
 'accountant',
 'air traffic controller',
 'analyst',
 'architect',
 'artist',
 'assistant',
 'attendant',
 'attorney',
 'auditor',
 'baker',
 'banker',
 'barber',
 'bartender',
 'bookkeeper',
 'businessperson',
 'butcher',
 'carpenter',
 'cashier',
 'chief',
 'cleaner',
 'clerk',
 'coach',
 'construction worker',
 'cook',
 'counselor',
 'dental hygienist',
 'dentist',
 'designer',
 'developer',
 'dietician',
 'doctor',
 'driver',
 'economist',
 'editor',
 'engineer',
 'farmer',
 'filmmaker',
 'fisherman',
 'guard',
 'hairdresser',
 'housekeeper',
 'janitor',
 'jeweler',
 'judge',
 'laborer',
 'lawyer',
 'librarian',
 'manager',
 'mechanic',
 'mover',
 'nurse',
 'nutritionist',
 'optician',
 'painter',
 'photographer',
 'physician',
 "physician's assistant",
 'pilot',
 'police officer',
 'politician',
 'professor',
 'programmer',
 'receptionist',
 'salesperson',
 'scholar',
 'scientist',
 'secretary',
 'sheriff',
 'singer',
 'supervisor',
 'surgeon',
 'tailor',
 'teacher',
 'therapist',
 'undertaker',
 'veterinarian',
 'videographer',
 'writer']

In [31]:
btcs = []
pairs = []
for mp in dft["mutant_prediction_stat"].values :
    if len(mp) > 0 :
        btc = 0
        pair = 0
        already_processed = []
        for k1 in key :
            for k2 in key :
                if k1 != k2 :
                    k = k1 + "-" + k2
                    if k1 > k2 :
                        k = k2 + "-" + k1
                    if k not in already_processed :
                        already_processed.append(k)

                        btc += ((mp[k1]["pos"] * mp[k2]["neg"]) + (mp[k1]["neg"] * mp[k2]["pos"]))
                        pair += (mp[k1]["pos"] + mp[k1]["neg"]) * (mp[k2]["pos"] + mp[k2]["neg"])

#         double_counting_divider = len(key) * (len(key)-1)
#         dp.append(int(_dp/double_counting_divider)) # we must divide the number with the number of key to reduce the double counting
        btcs.append(btc)
        pairs.append(pair)
    else :
        btcs.append(0)
        pairs.append(0)

In [32]:
dft["btc"] = btcs
dft["possible_pair"] = pairs
dft

,label,template,original,template_id,mutant_example,mutant_prediction_stat,btc,possible_pair
0,0,"b "" ' A New Generation ' is the third Amityvil...","b "" ' A New Generation ' is the third Amityvil...",0,"{'CEO': 'b "" ' A New Generation ' is the third...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
1,1,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1,"{'CEO': 'b "" At first I thought this film was ...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",78,3081
2,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",2,"{'CEO': 'b "" Compared to the acclaimed Hollywo...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
3,1,"b "" First of all, ignore the comment about how...","b "" First of all, ignore the comment about how...",3,"{'CEO': 'b "" First of all, ignore the comment ...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
4,1,"b "" First off let me say that this is probably...","b "" First off let me say that this is probably...",4,"{'CEO': 'b "" First off let me say that this is...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
5,0,"b "" I bought the DVD out of a big bin for$ 4.9...","b "" I bought the DVD out of a big bin for$ 4.9...",5,"{'CEO': 'b "" I bought the DVD out of a big bin...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
6,0,"b "" I only comment on really very good films a...","b "" I only comment on really very good films a...",6,"{'CEO': 'b "" I only comment on really very goo...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
7,1,"b "" I'm pleased that this was the work of fore...","b "" I'm pleased that this was the work of fore...",7,"{'CEO': 'b "" I'm pleased that this was the wor...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
8,0,"b "" Kevin Spacey is my favorite @OCCUPATION of...","b "" Kevin Spacey is my favorite actor of all t...",8,"{'CEO': 'b "" Kevin Spacey is my favorite CEO o...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
9,1,"b "" One day a red alley cat is fed up of being...","b "" One day a red alley cat is fed up of being...",9,"{'CEO': 'b "" One day a red alley cat is fed up...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
10,0,"b "" The Patriot (nothing to do with the Mel Gi...","b "" The Patriot ( nothing to do with the Mel G...",10,"{'CEO': 'b "" The Patriot (nothing to do with t...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
11,1,"b "" There are 3 of these movies, all similarly...","b "" There are 3 of these movies, all similarly...",11,"{'CEO': 'b "" There are 3 of these movies, all ...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
12,0,"b "" This movie is one of the worse movies of a...","b "" This movie is one of the worse movies of a...",12,"{'CEO': 'b "" This movie is one of the worse mo...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
13,0,"b "" This movie was a major bait and switch. I ...","b "" This movie was a major bait and switch. I ...",13,"{'CEO': 'b "" This movie was a major bait and s...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
14,1,"b "" This movie was beautiful and touching. It ...","b "" This movie was beautiful and touching. It ...",14,"{'CEO': 'b "" This movie was beautiful and touc...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
15,1,"b "" This was really one of the most enjoyable ...","b "" This was really one of the most enjoyable ...",15,"{'CEO': 'b "" This was really one of the most e...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
16,1,"b "" When it was released, in the beginning of ...","b "" When it was released, in the beginning of ...",16,"{'CEO': 'b "" When it was released, in the begi...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
17,0,"b "" wow, i just got one watching this. How CRA...","b "" wow, i just got one watching this. How CRA...",17,"{'CEO': 'b "" wow, i just got one watching this...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
18,0,b ' A comedy that spoofs the inspirational spo...,b ' A comedy that spoofs the inspirational spo...,18,{'CEO': 'b ' A comedy that spoofs the inspirat...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
19,1,b ' A dangerous psychopathic killer Jacob Good...,b ' A dangerous psychopathic killer Jacob Good...,19,{'CEO': 'b ' A dangerous psychopathic killer J...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
20,0,b ' Attractive husband and wife writing team R...,b ' Attractive husband and wife writing team R...,20,{'CEO': 'b ' Attractive husband and wife writi...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
21,1,"b ' Billy Crystal is Larry, @DetAAN @OCCUPATIO...","b ' Billy Crystal is Larry, a writer who hasn'...",21,"{'CEO': 'b ' Billy Crystal is Larry, a CEO who...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
22,0,"b ' Brainy, cross - dressing little boy finds ...","b ' Brainy, cross - dressing little boy finds ...",22,"{'CEO': 'b ' Brainy, cross - dressing little b...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
23,0,b ' Even my five year old was bored. Very pred...,b ' Even my five year old was bored. Very pred...,23,{'CEO': 'b ' Even my five year old was bored. ...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
24,1,b ' Every review I have read so far seems to h...,b ' Every review I have read so far seems to h...,24,{'CEO': 'b ' Every review I have read so far s...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
25,1,"b ' For those of you still in the dark, I will...","b ' For those of you still in the dark, I will...",25,{'CEO': 'b ' For those of you still in the dar...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
26,0,b ' French Cinema sucks! Down with all these p...,b ' French Cinema sucks! Down with all these p...,26,{'CEO': 'b ' French Cinema sucks! Down with al...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
27,1,b ' German - born Turkish @OCCUPATION Faith Ak...,b ' German - born Turkish director Faith Akin ...,27,{'CEO': 'b ' German - born Turkish CEO Faith A...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
28,1,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,28,{'CEO': 'b ' Great underrated movie great acti...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",228,3081
29,0,"b ' Here's example number 87,358 of Hollywood'...","b ' Here's example number 87,358 of Hollywood'...",29,"{'CEO': 'b ' Here's example number 87,358 of H...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
30,1,"b ' Hey all you jive hustlers, you stone foxes...","b ' Hey all you jive hustlers, you stone foxes...",30,"{'CEO': 'b ' Hey all you jive hustlers, you st...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
31,0,"b ' I happened to catch this on TV, and wanted...","b ' I happened to catch this on TV, and wanted...",31,"{'CEO': 'b ' I happened to catch this on TV, a...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
32,0,b ' I remember watching this movie on TV a few...,b ' I remember watching this movie on TV a few...,32,{'CEO': 'b ' I remember watching this movie on...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
33,1,b ' I tivo'd this on Turner Classic just becau...,b ' I tivo'd this on Turner Classic just becau...,33,{'CEO': 'b ' I tivo'd this on Turner Classic j...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
34,0,b ' If this film were to be rated on a scale o...,b ' If this film were to be rated on a scale o...,34,{'CEO': 'b ' If this film were to be rated on ...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
35,0,b ' Jackie Chan movies are typical examples of...,b ' Jackie Chan movies are typical examples of...,35,{'CEO': 'b ' Jackie Chan movies are typical ex...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
36,1,"b ' KRAMER VS KRAMER won five Oscars, includin...","b ' KRAMER VS KRAMER won five Oscars, includin...",36,"{'CEO': 'b ' KRAMER VS KRAMER won five Oscars,...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
37,0,"b ' Like many, this dung heap caught my eye wh...","b ' Like many, this dung heap caught my eye wh...",37,"{'CEO': 'b ' Like many, this dung heap caught ...","{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
38,1,"b ' My favorite show of all time! Yeah, I thou...","b ' My favorite show of all time! Yeah, I thou...",38,{'CEO': 'b ' My favorite show of all time! Yea...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
39,0,b ' Perhaps the wildest outlier in Alfred Hitc...,b ' Perhaps the wildest outlier in Alfred Hitc...,39,{'CEO': 'b ' Perhaps the wildest outlier in Al...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
40,1,"b ' Ponyo, written and directed by Hayao Miyaz...","b ' Ponyo, written and directed by Hayao Miyaz...",40,"{'CEO': 'b ' Ponyo, written and directed by Ha...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
41,0,b ' The actors are so bland that it's almost i...,b ' The actors are so bland that it's almost i...,41,{'CEO': 'b ' The actors are so bland that it's...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
42,0,b ' The biggest problem with this film is that...,b ' The biggest problem with this film is that...,42,{'CEO': 'b ' The biggest problem with this fil...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
43,1,b ' This film is great with some of the best s...,b ' This film is great with some of the best s...,43,{'CEO': 'b ' This film is great with some of t...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",0,3081
44,0,b ' What about Scream Baby Scream is supposed ...,b ' What about Scream Baby Scream is supposed ...,44,{'CEO': 'b ' What about Scream Baby Scream is ...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081
45,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,45,{'CEO': 'b ' What symbolism! exclaimed a woman...,"{'CEO': {'pos': 0, 'neg': 1}, 'accountant': {'...",0,3081

### Number of Bias-Uncovering Test Case

In [35]:
int(dft["btc"].sum())

306

### BTC Rate

In [36]:
dft["btc"].sum() / dft["possible_pair"].sum()

0.0021590957199102492

### Get Data that Have number of BTC more than one

In [37]:
d = dft[dft["btc"] > 0]
d

,label,template,original,template_id,mutant_example,mutant_prediction_stat,btc,possible_pair
1,1,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1,"{'CEO': 'b "" At first I thought this film was ...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",78,3081
28,1,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,28,{'CEO': 'b ' Great underrated movie great acti...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",228,3081

In [38]:
# d.to_csv("142_templates_generate_BTC.csv")

### Sort Data based on the number of BTC

In [39]:
d = d.sort_values(["btc", "template"], ascending=False)
d = d.reset_index(drop=True)
d

,label,template,original,template_id,mutant_example,mutant_prediction_stat,btc,possible_pair
0,1,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,28,{'CEO': 'b ' Great underrated movie great acti...,"{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",228,3081
1,1,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1,"{'CEO': 'b "" At first I thought this film was ...","{'CEO': {'pos': 1, 'neg': 0}, 'accountant': {'...",78,3081

In [40]:
# d.groupby("template_id").get_group(2760).iloc[0]["mutant_example"]

In [41]:
# d.groupby("template_id").get_group(2760).iloc[0]["template"]

### Get Data BTC for train and test

In [42]:
df

,label,mutant,mtnt,template,original,occupation,prediction,template_id
0,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,attendant,0,45
1,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,cashier,0,45
2,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,teacher,0,45
3,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,nurse,0,45
4,0,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,b ' What symbolism! exclaimed a woman as we ex...,assistant,0,45
...,...,...,...,...,...,...,...,...
3629,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",nutritionist,1,2
3630,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",photographer,1,2
3631,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",police officer,1,2
3632,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",singer,1,2
3633,1,"b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...","b "" Compared to the acclaimed Hollywood remake...",undertaker,1,2

In [43]:
template_that_produce_btc = d["template_id"].tolist()
# template_that_produce_btc

In [44]:
start = time.time()

mutant_text_1 = []
mutant_text_2 = []
prediction_1 = []
prediction_2 = []
identifier_1 = []
identifier_2 = []
template = []
original = []
label = []
for i in template_that_produce_btc: # only processing from template that produce BTC
    data = gb.get_group(i)
    dc = data.groupby(identifier)
    already_processed = []
    for k1, v1 in dict(iter(dc)).items() :
        for k2, v2 in dict(iter(dc)).items() :
            if k1 != k2 :
                key = k1 + "-" + k2
                if k1 > k2 :
                    key = k2 + "-" + k1
                if key not in already_processed :
                    already_processed.append(key)
                    for m_1, p_1, i_1, t, o, l in zip(v1["mutant"].values, v1["prediction"].values, v1[identifier].values, v1["template"].values, v1["original"].values, v1["label"].values) :
                        for m_2, p_2, i_2 in zip(v2["mutant"].values, v2["prediction"].values, v2[identifier].values) :
                            if p_1 != p_2 : # only add discordant pairs
                                mutant_text_1.append(m_1)
                                prediction_1.append(p_1)
                                identifier_1.append(i_1)
                                mutant_text_2.append(m_2)
                                prediction_2.append(p_2)
                                identifier_2.append(i_2)
                                template.append(t)
                                original.append(o)
                                label.append(l)

end = time.time()
print("Execution time: ", end-start)

Execution time:  3.857818126678467

In [48]:
btc = pd.DataFrame(data={"mutant_1" : mutant_text_1, "mutant_2" : mutant_text_2, "prediction_1": prediction_1, "prediction_2" : prediction_2, "identifier_1": identifier_1, "identifier_2" : identifier_2, "template": template, "original":original, "label": label})

btc

,mutant_1,mutant_2,prediction_1,prediction_2,identifier_1,identifier_2,template,original,label
0,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1,0,CEO,developer,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1
1,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1,0,CEO,filmmaker,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1
2,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1,0,CEO,programmer,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1
3,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1,0,accountant,developer,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1
4,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1,0,accountant,filmmaker,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1
...,...,...,...,...,...,...,...,...,...
301,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",0,1,dental hygienist,therapist,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1
302,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",0,1,dental hygienist,undertaker,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1
303,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",0,1,dental hygienist,veterinarian,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1
304,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",0,1,dental hygienist,videographer,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1
305,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",0,1,dental hygienist,writer,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1

In [49]:
btc.to_csv("btc-occupation.csv")

In [46]:
import os

base_dir = "../../data/btc/biasfinder/occupation/"
data_dir = base_dir + "full/"

if not os.path.exists(data_dir) :
    os.makedirs(data_dir)


train = btc.sample(frac=1, random_state=123)
train.to_csv(data_dir + "train.csv", index=None, header=None, sep="\t")

btc.to_csv(data_dir + "test.csv", index=None, header=None, sep="\t")

In [47]:
pd.read_csv(base_dir + "full/test.csv", sep="\t")

,b ' Great underrated movie great action good actors and a wonderful story line. Wesley is verry good and the CEO the bad guy is wonderful The girl plays a nice role and the comedy mixed with blakness! ',b ' Great underrated movie great action good actors and a wonderful story line. Wesley is verry good and the developer the bad guy is wonderful The girl plays a nice role and the comedy mixed with blakness! ',1,0,CEO,developer,b ' Great underrated movie great action good actors and a wonderful story line. Wesley is verry good and the @OCCUPATION the bad guy is wonderful The girl plays a nice role and the comedy mixed with blakness! ',b ' Great underrated movie great action good actors and a wonderful story line. Wesley is verry good and the villain the bad guy is wonderful The girl plays a nice role and the comedy mixed with blakness! ',1.1
0,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1,0,CEO,filmmaker,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1
1,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1,0,CEO,programmer,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1
2,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1,0,accountant,developer,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1
3,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1,0,accountant,filmmaker,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1
4,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1,0,accountant,programmer,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1
...,...,...,...,...,...,...,...,...,...
300,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",0,1,dental hygienist,therapist,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1
301,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",0,1,dental hygienist,undertaker,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1
302,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",0,1,dental hygienist,veterinarian,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1
303,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",0,1,dental hygienist,videographer,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1
304,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",0,1,dental hygienist,writer,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1

In [109]:
m1 = btc.iloc[:,[-1,0]]
m1 = m1.rename(columns={"mutant_1": "text"})
m2 = btc.iloc[:,[-1,1]]
m2 = m2.rename(columns={"mutant_2": "text"})

m1

     label                                               text
184      1  b ' Great underrated movie great action good a...
239      0  b ' It's painfully clear that all effort in th...
170      1  b ' Great underrated movie great action good a...
261      0  b ' It's painfully clear that all effort in th...
374      1  b " At first I thought this film was going to ...
..     ...                                                ...
230      0  b ' It's painfully clear that all effort in th...
98       1  b ' Great underrated movie great action good a...
322      1  b " At first I thought this film was going to ...
382      1  b " At first I thought this film was going to ...
365      1  b " At first I thought this film was going to ...

[384 rows x 2 columns]

In [97]:
data = pd.concat([m1, m2])
data

     label                                               text
0        1  b ' Great underrated movie great action good a...
1        1  b ' Great underrated movie great action good a...
2        1  b ' Great underrated movie great action good a...
3        1  b ' Great underrated movie great action good a...
4        1  b ' Great underrated movie great action good a...
..     ...                                                ...
379      1  b " At first I thought this film was going to ...
380      1  b " At first I thought this film was going to ...
381      1  b " At first I thought this film was going to ...
382      1  b " At first I thought this film was going to ...
383      1  b " At first I thought this film was going to ...

[768 rows x 2 columns]

In [98]:
# data["text"] = data["text"].astype("category")
# data["text_id"] = data["text"].cat.codes
# data

In [99]:
unique_data = data.drop_duplicates().reset_index(drop=True)
unique_data

     label                                               text
0        1  b ' Great underrated movie great action good a...
1        1  b ' Great underrated movie great action good a...
2        1  b ' Great underrated movie great action good a...
3        1  b ' Great underrated movie great action good a...
4        1  b ' Great underrated movie great action good a...
..     ...                                                ...
232      1  b " At first I thought this film was going to ...
233      1  b " At first I thought this film was going to ...
234      1  b " At first I thought this film was going to ...
235      1  b " At first I thought this film was going to ...
236      1  b " At first I thought this film was going to ...

[237 rows x 2 columns]

In [100]:
unique_data[unique_data["label"] == 0]

     label                                               text
63       0  b ' It's painfully clear that all effort in th...
64       0  b ' It's painfully clear that all effort in th...
65       0  b ' It's painfully clear that all effort in th...
66       0  b ' It's painfully clear that all effort in th...
67       0  b ' It's painfully clear that all effort in th...
..     ...                                                ...
180      0  b ' It's painfully clear that all effort in th...
181      0  b ' It's painfully clear that all effort in th...
182      0  b ' It's painfully clear that all effort in th...
183      0  b ' It's painfully clear that all effort in th...
184      0  b ' It's painfully clear that all effort in th...

[79 rows x 2 columns]

In [101]:
import os

data_dir = base_dir + "unique/"

if not os.path.exists(data_dir) :
    os.makedirs(data_dir)

# train = unique_data
train = unique_data.sample(frac=1, random_state=123)
train.to_csv(data_dir + "train.csv", index=None, header=None, sep="\t")

test = data
test.to_csv(data_dir + "test.csv", index=None, header=None, sep="\t")

In [102]:
btc

,mutant_1,mutant_2,prediction_1,prediction_2,identifier_1,identifier_2,template,original,label
0,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1,0,CEO,developer,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1
1,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1,0,CEO,filmmaker,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1
2,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1,0,CEO,programmer,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1
3,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1,0,accountant,developer,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1
4,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1,0,accountant,filmmaker,b ' Great underrated movie great action good a...,b ' Great underrated movie great action good a...,1
...,...,...,...,...,...,...,...,...,...
379,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",0,1,dental hygienist,therapist,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1
380,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",0,1,dental hygienist,undertaker,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1
381,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",0,1,dental hygienist,veterinarian,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1
382,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",0,1,dental hygienist,videographer,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1
383,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",0,1,dental hygienist,writer,"b "" At first I thought this film was going to ...","b "" At first I thought this film was going to ...",1

In [103]:
btc = btc.sample(frac=1, random_state=123)

texts = []
templates = []
for index, rows in btc[:50].iterrows():
    texts.append(rows["original"])
    texts.append(rows["mutant_1"])
    texts.append(rows["mutant_2"])
    templates.append(rows["template"])

In [104]:
# texts

In [105]:
user_study = pd.DataFrame(data={"text":texts})
template = pd.DataFrame(data={"template":templates})

In [106]:
user_study

                                                  text
0    b ' Great underrated movie great action good a...
1    b ' Great underrated movie great action good a...
2    b ' Great underrated movie great action good a...
3    b ' It's painfully clear that all effort in th...
4    b ' It's painfully clear that all effort in th...
..                                                 ...
145  b ' Great underrated movie great action good a...
146  b ' Great underrated movie great action good a...
147  b ' It's painfully clear that all effort in th...
148  b ' It's painfully clear that all effort in th...
149  b ' It's painfully clear that all effort in th...

[150 rows x 1 columns]

In [107]:
user_study.to_csv("user_study_occupation.csv")
template.to_csv("template_occupation.csv")