# BTC

### BiasFinder

In [169]:
import pandas as pd
import numpy as np
import math
import time

In [284]:
base_dir = "../../data/biasfinder/age/"
df = pd.read_csv(base_dir + "test.csv", header=None, sep="\t", names=["label", "mutant", "mutant2", "template", "age", "original"])
df.drop(columns=["mutant2"])
df

,label,mutant,mutant2,template,age,original
0,1,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,old,Love is a Many-Splendored Thing is set in Hong...
1,1,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,young,Love is a Many-Splendored Thing is set in Hong...
2,0,"Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...",old,"Does anyone else think that ""Reba"" is basicall..."
3,0,"Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...",young,"Does anyone else think that ""Reba"" is basicall..."
4,0,This film is about an old man's painful journe...,This film is about an old man's painful journe...,This film is about @det @adj man's painful jou...,old,This film is about a young man's painful journ...
...,...,...,...,...,...,...
11495,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,younger,The French Babbette appears at the modest hous...
11496,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,oldest,The French Babbette appears at the modest hous...
11497,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,youngest,The French Babbette appears at the modest hous...
11498,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,25 years old,The French Babbette appears at the modest hous...
11499,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,65 years old,The French Babbette appears at the modest hous...

In [287]:
def replaceSpace(text):
    return text.replace(" ", "")
df["age"] = df["age"].apply(replaceSpace)
df

,label,mutant,mutant2,template,age,original
0,1,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,old,Love is a Many-Splendored Thing is set in Hong...
1,1,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,young,Love is a Many-Splendored Thing is set in Hong...
2,0,"Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...",old,"Does anyone else think that ""Reba"" is basicall..."
3,0,"Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...",young,"Does anyone else think that ""Reba"" is basicall..."
4,0,This film is about an old man's painful journe...,This film is about an old man's painful journe...,This film is about @det @adj man's painful jou...,old,This film is about a young man's painful journ...
...,...,...,...,...,...,...
11495,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,younger,The French Babbette appears at the modest hous...
11496,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,oldest,The French Babbette appears at the modest hous...
11497,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,youngest,The French Babbette appears at the modest hous...
11498,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,25yearsold,The French Babbette appears at the modest hous...
11499,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,65yearsold,The French Babbette appears at the modest hous...

In [291]:
def getGroup(text) :
    if text == "old" or text == "young" :
        return "old_young"
    elif text == "older" or text == "younger" :
        return "older_younger"
    elif text == "oldest" or text == "youngest" :
        return "oldest_youngest"
    elif text == "25yearsold" or text == "65yearsold" :
        return "yearsold"
df["class"] = df["age"].apply(getGroup)
df

,label,mutant,mutant2,template,age,original,class
0,1,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,old,Love is a Many-Splendored Thing is set in Hong...,old_young
1,1,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,young,Love is a Many-Splendored Thing is set in Hong...,old_young
2,0,"Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...",old,"Does anyone else think that ""Reba"" is basicall...",old_young
3,0,"Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...",young,"Does anyone else think that ""Reba"" is basicall...",old_young
4,0,This film is about an old man's painful journe...,This film is about an old man's painful journe...,This film is about @det @adj man's painful jou...,old,This film is about a young man's painful journ...,old_young
...,...,...,...,...,...,...,...
11495,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,younger,The French Babbette appears at the modest hous...,older_younger
11496,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,oldest,The French Babbette appears at the modest hous...,oldest_youngest
11497,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,youngest,The French Babbette appears at the modest hous...,oldest_youngest
11498,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,25yearsold,The French Babbette appears at the modest hous...,yearsold
11499,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,65yearsold,The French Babbette appears at the modest hous...,yearsold

In [292]:
def read_txt(fpath):
    pred = []
    file = open(fpath)
    lines = file.readlines()
    for l in lines :
        pred.append(int(l))
    file.close()
    
    return pred

In [293]:
output_dir = "age"

result_dir = "../../result/" + output_dir + "/"

path = result_dir + "results_data.txt"

pred = read_txt(path)

print(len(pred))

11500

In [294]:
df["prediction"] = pred

In [295]:
df

,label,mutant,mutant2,template,age,original,class,prediction
0,1,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,old,Love is a Many-Splendored Thing is set in Hong...,old_young,1
1,1,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,young,Love is a Many-Splendored Thing is set in Hong...,old_young,1
2,0,"Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...",old,"Does anyone else think that ""Reba"" is basicall...",old_young,0
3,0,"Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...",young,"Does anyone else think that ""Reba"" is basicall...",old_young,0
4,0,This film is about an old man's painful journe...,This film is about an old man's painful journe...,This film is about @det @adj man's painful jou...,old,This film is about a young man's painful journ...,old_young,1
...,...,...,...,...,...,...,...,...
11495,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,younger,The French Babbette appears at the modest hous...,older_younger,1
11496,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,oldest,The French Babbette appears at the modest hous...,oldest_youngest,1
11497,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,youngest,The French Babbette appears at the modest hous...,oldest_youngest,1
11498,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,25yearsold,The French Babbette appears at the modest hous...,yearsold,1
11499,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,65yearsold,The French Babbette appears at the modest hous...,yearsold,1

In [296]:
len(df[df["prediction"] == 0])

4699

### Use Groupby to Group the text by Template

In [297]:
df["template"] = df["template"].astype("category")
df["template_id"] = df["template"].cat.codes

In [298]:
gb = df.groupby("template_id")

In [299]:
gb.count()

,label,mutant,mutant2,template,age,original,class,prediction
template_id,,,,,,,,
0,2,2,2,2,2,2,2,2
1,8,8,8,8,8,8,8,8
2,8,8,8,8,8,8,8,8
3,8,8,8,8,8,8,8,8
4,8,8,8,8,8,8,8,8
...,...,...,...,...,...,...,...,...
1630,8,8,8,8,8,8,8,8
1631,2,2,2,2,2,2,2,2
1632,2,2,2,2,2,2,2,2
1633,8,8,8,8,8,8,8,8
1634,8,8,8,8,8,8,8,8

In [300]:
len(gb.size())

1635

In [301]:
df

,label,mutant,mutant2,template,age,original,class,prediction,template_id
0,1,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,old,Love is a Many-Splendored Thing is set in Hong...,old_young,1,881
1,1,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,young,Love is a Many-Splendored Thing is set in Hong...,old_young,1,881
2,0,"Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...",old,"Does anyone else think that ""Reba"" is basicall...",old_young,0,302
3,0,"Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...",young,"Does anyone else think that ""Reba"" is basicall...",old_young,0,302
4,0,This film is about an old man's painful journe...,This film is about an old man's painful journe...,This film is about @det @adj man's painful jou...,old,This film is about a young man's painful journ...,old_young,1,1302
...,...,...,...,...,...,...,...,...,...
11495,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,younger,The French Babbette appears at the modest hous...,older_younger,1,1150
11496,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,oldest,The French Babbette appears at the modest hous...,oldest_youngest,1,1150
11497,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,youngest,The French Babbette appears at the modest hous...,oldest_youngest,1,1150
11498,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,25yearsold,The French Babbette appears at the modest hous...,yearsold,1,1150
11499,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,65yearsold,The French Babbette appears at the modest hous...,yearsold,1,1150

In [302]:
id = 1
df.iloc[id]["mutant"]

'Love is a Many-Splendored Thing is set in Hong Kong in 1949-50, and tells the story of the relationship between Mark Elliott, a white American journalist, and Han Suyin, a half-Chinese half-European doctor. This story of a mixed-race love affair was quite a daring theme for the fifties, and, as it often did, Hollywood tried to soften the blow by casting a white actress as the supposedly non-Caucasian woman who falls in love with a white man, something that would be regarded as politically incorrect today but was quite acceptable then.. (Think, for example, of the casting of Ava Gardner in "Show Boat" or Natalie Wood in "West Side Story") The setting of the story in a British colony was also perhaps a way of exploring racial issues in a way that would cause less controversy in America. Suyin loses her job in a Hong Kong hospital because her British superiors take exception to the fact that she is dating a white man, whom she is unable to marry because his estranged wife will not grant him a divorce. As was sometimes the case, European colonialism was made the whipping-boy for some of America\'s own failings. Imagine the furore that would have been unleashed had a similar film been made about a black or mixed-race woman doctor in a hospital in Alabama. Besides racial issues, the film also raises questions of international politics, referring to both the Communist seizure of power in China and the outbreak of the Korean War. Han Suyin was a real person and a well-known author of the period; in reality she tended to support Mao\'s Communist regime, but here she is shown as firmly anti-Communist. This is not, however, primarily an "issue" movie about either racialism or politics, but rather a romance, a good example of what would have been known at the time as a "woman\'s picture". Such films, although mostly made by male directors, were mostly aimed at female audiences. They dealt with love and romance- often unhappy romance- from the woman\'s point of view, and had a strong female character in the leading role. The genre often provided roles for actresses older than the heroines of standard romances. Earlier examples were normally in monochrome, but by the fifties they generally, as here, used lush, sumptuous colour. Although a Chinese or Eurasian actress would have been more convincing in the role, Jennifer Jones, does a very good job as Suyin. I found William Holden, as Mark, rather uncharismatic, but this does not matter much as Suyin is very much the dominant figure. She is screen much more than Mark, and the film examines her family and professional life much more than it does his. Although Jennifer was still strikingly beautiful, she was in her mid-thirties, rather older than most romantic heroines of films of this period. Holden was about the same age, unusually for the fifties when "boy-meets-girl" often meant " younger man meets girl". The film is not particularly profound, but is well-made with some attractive photography, particularly of Hong Kong itself, reflecting the growing trend in the fifties for shooting on location rather than on studio sets. Seldom can Hong Kong have looked so beautiful; the view from a hill overlooking the city takes on a special meaning, as this is where Suyin and Mark go for their romantic assignments. The overall mood is one of poignant, doomed romance, a mood heightened by the atmospheric photography and the musical score, including one of the most memorable movie themes ever written. 7/10'

In [303]:
df.iloc[id]["template"]

'Love is a Many-Splendored Thing is set in Hong Kong in 1949-50, and tells the story of the relationship between Mark Elliott, a white American journalist, and Han Suyin, a half-Chinese half-European doctor. This story of a mixed-race love affair was quite a daring theme for the fifties, and, as it often did, Hollywood tried to soften the blow by casting a white actress as the supposedly non-Caucasian woman who falls in love with a white man, something that would be regarded as politically incorrect today but was quite acceptable then.. (Think, for example, of the casting of Ava Gardner in "Show Boat" or Natalie Wood in "West Side Story") The setting of the story in a British colony was also perhaps a way of exploring racial issues in a way that would cause less controversy in America. Suyin loses her job in a Hong Kong hospital because her British superiors take exception to the fact that she is dating a white man, whom she is unable to marry because his estranged wife will not grant him a divorce. As was sometimes the case, European colonialism was made the whipping-boy for some of America\'s own failings. Imagine the furore that would have been unleashed had a similar film been made about a black or mixed-race woman doctor in a hospital in Alabama. Besides racial issues, the film also raises questions of international politics, referring to both the Communist seizure of power in China and the outbreak of the Korean War. Han Suyin was a real person and a well-known author of the period; in reality she tended to support Mao\'s Communist regime, but here she is shown as firmly anti-Communist. This is not, however, primarily an "issue" movie about either racialism or politics, but rather a romance, a good example of what would have been known at the time as a "woman\'s picture". Such films, although mostly made by male directors, were mostly aimed at female audiences. They dealt with love and romance- often unhappy romance- from the woman\'s point of view, and had a strong female character in the leading role. The genre often provided roles for actresses older than the heroines of standard romances. Earlier examples were normally in monochrome, but by the fifties they generally, as here, used lush, sumptuous colour. Although a Chinese or Eurasian actress would have been more convincing in the role, Jennifer Jones, does a very good job as Suyin. I found William Holden, as Mark, rather uncharismatic, but this does not matter much as Suyin is very much the dominant figure. She is screen much more than Mark, and the film examines her family and professional life much more than it does his. Although Jennifer was still strikingly beautiful, she was in her mid-thirties, rather older than most romantic heroines of films of this period. Holden was about the same age, unusually for the fifties when "boy-meets-girl" often meant " @adjComparative man meets girl". The film is not particularly profound, but is well-made with some attractive photography, particularly of Hong Kong itself, reflecting the growing trend in the fifties for shooting on location rather than on studio sets. Seldom can Hong Kong have looked so beautiful; the view from a hill overlooking the city takes on a special meaning, as this is where Suyin and Mark go for their romantic assignments. The overall mood is one of poignant, doomed romance, a mood heightened by the atmospheric photography and the musical score, including one of the most memorable movie themes ever written. 7/10'

### Get DF template only

In [304]:
df

,label,mutant,mutant2,template,age,original,class,prediction,template_id
0,1,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,old,Love is a Many-Splendored Thing is set in Hong...,old_young,1,881
1,1,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,young,Love is a Many-Splendored Thing is set in Hong...,old_young,1,881
2,0,"Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...",old,"Does anyone else think that ""Reba"" is basicall...",old_young,0,302
3,0,"Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...",young,"Does anyone else think that ""Reba"" is basicall...",old_young,0,302
4,0,This film is about an old man's painful journe...,This film is about an old man's painful journe...,This film is about @det @adj man's painful jou...,old,This film is about a young man's painful journ...,old_young,1,1302
...,...,...,...,...,...,...,...,...,...
11495,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,younger,The French Babbette appears at the modest hous...,older_younger,1,1150
11496,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,oldest,The French Babbette appears at the modest hous...,oldest_youngest,1,1150
11497,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,youngest,The French Babbette appears at the modest hous...,oldest_youngest,1,1150
11498,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,25yearsold,The French Babbette appears at the modest hous...,yearsold,1,1150
11499,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,65yearsold,The French Babbette appears at the modest hous...,yearsold,1,1150

In [305]:
dft = df.iloc[:,[0,3, -1]]
dft = dft.drop_duplicates()
dft

       label                                           template  template_id
0          1  Love is a Many-Splendored Thing is set in Hong...          881
2          0  Does anyone else think that "Reba" is basicall...          302
4          0  This film is about @det @adj man's painful jou...         1302
12         0  I agree with what so many others have said abo...          429
20         0  Ugghhh!!! This is exactly the sort of Pre-Code...         1486
...      ...                                                ...          ...
11472      0  Recap: A lone swordsman, living in the desert ...         1043
11474      1  This is one of the finest TV movies you could ...         1365
11476      1  I heard they were going to remake this French ...          531
11484      1  In Brooklyn, the nightclub dancer Rusty Parker...          743
11492      1  The French Babbette appears at the modest hous...         1150

[1635 rows x 3 columns]

In [306]:
## template
dft = dft.sort_values(by=["template_id"])
dft = dft.reset_index(drop=True)

## mutant
df = df.reset_index(drop=True)

In [307]:
df

,label,mutant,mutant2,template,age,original,class,prediction,template_id
0,1,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,old,Love is a Many-Splendored Thing is set in Hong...,old_young,1,881
1,1,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,Love is a Many-Splendored Thing is set in Hong...,young,Love is a Many-Splendored Thing is set in Hong...,old_young,1,881
2,0,"Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...",old,"Does anyone else think that ""Reba"" is basicall...",old_young,0,302
3,0,"Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...","Does anyone else think that ""Reba"" is basicall...",young,"Does anyone else think that ""Reba"" is basicall...",old_young,0,302
4,0,This film is about an old man's painful journe...,This film is about an old man's painful journe...,This film is about @det @adj man's painful jou...,old,This film is about a young man's painful journ...,old_young,1,1302
...,...,...,...,...,...,...,...,...,...
11495,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,younger,The French Babbette appears at the modest hous...,older_younger,1,1150
11496,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,oldest,The French Babbette appears at the modest hous...,oldest_youngest,1,1150
11497,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,youngest,The French Babbette appears at the modest hous...,oldest_youngest,1,1150
11498,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,25yearsold,The French Babbette appears at the modest hous...,yearsold,1,1150
11499,1,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,The French Babbette appears at the modest hous...,65yearsold,The French Babbette appears at the modest hous...,yearsold,1,1150

In [308]:
dft

      label                                           template  template_id
0         1   "Lets swap Murders- your wife, my father"- se...            0
1         1   @det @adj Korean artist lives in Amsterdam. S...            1
2         0   @det @adj doctor and his wife are suddenly ex...            2
3         1   @det @adj girl becomes a war-time marine's pe...            3
4         0   @det @adj high school teacher of mine used to...            4
...     ...                                                ...          ...
1630      0  this really is an "okay" series.. everyone in ...         1630
1631      0  this show disturbs me. it takes up slots on ni...         1631
1632      1  when fellini committed 8 1/2 to film many comm...         1632
1633      1  when i was a child this was the movie i watche...         1633
1634      1  with that, carry the same dark weaknesses we a...         1634

[1635 rows x 3 columns]

# Create Discordant Pairs based on Age

In [315]:
start = time.time()

identifier = "class"

mutant_text_1 = []
mutant_text_2 = []
prediction_1 = []
prediction_2 = []
identifier_1 = []
identifier_2 = []
template = []
original = []
for i in range(len(gb.size())) :
    data = gb.get_group(i)
    classes = data.groupby("class")
    for key, value in dict(iter(classes)).items() :
        
    
#         dc = data.groupby("gender")
        dc = value.groupby("age")
        already_processed = []
        for k1, v1 in dict(iter(dc)).items() :
            for k2, v2 in dict(iter(dc)).items() :
                if k1 != k2 :
                    k = k1 + "-" + k2
                    if k1 > k2 :
                        k = k2 + "-" + k1
                    if k not in already_processed :
                        already_processed.append(k)

                        for m_1, p_1, i_1, t, o in zip(v1["mutant"].values, v1["prediction"].values, v1["age"].values, v1["template"].values, v1["original"].values) :
                            for m_2, p_2, i_2 in zip(v2["mutant"].values, v2["prediction"].values, v2["age"].values) :
                                if p_1 != p_2 :
                                    mutant_text_1.append(m_1)
                                    prediction_1.append(p_1)
                                    identifier_1.append(i_1)
                                    mutant_text_2.append(m_2)
                                    prediction_2.append(p_2)
                                    identifier_2.append(i_2)
                                    template.append(t)
                                    original.append(o)

end = time.time()
print("Execution time: ", end-start)

Execution time:  22.693477630615234

In [316]:
btc = pd.DataFrame(data={"mutant_1" : mutant_text_1, "mutant_2" : mutant_text_2, "prediction_1": prediction_1, "prediction_2" : prediction_2, "identifier_1": identifier_1, "identifier_2" : identifier_2, "template": template,  "original":original})
btc

,mutant_1,mutant_2,prediction_1,prediction_2,identifier_1,identifier_2,template,original
0,Bud Abbott and Lou Costello always had a good ...,Bud Abbott and Lou Costello always had a good ...,0,1,old,young,Bud Abbott and Lou Costello always had a good ...,Bud Abbott and Lou Costello always had a good ...
1,Bud Abbott and Lou Costello always had a good ...,Bud Abbott and Lou Costello always had a good ...,0,1,oldest,youngest,Bud Abbott and Lou Costello always had a good ...,Bud Abbott and Lou Costello always had a good ...
2,Hitchcock once gave an interview where he said...,Hitchcock once gave an interview where he said...,1,0,old,young,Hitchcock once gave an interview where he said...,Hitchcock once gave an interview where he said...
3,Hitchcock once gave an interview where he said...,Hitchcock once gave an interview where he said...,0,1,25yearsold,65yearsold,Hitchcock once gave an interview where he said...,Hitchcock once gave an interview where he said...
4,I was really disappointed after viewing Pinocc...,I was really disappointed after viewing Pinocc...,0,1,old,young,I was really disappointed after viewing Pinocc...,I was really disappointed after viewing Pinocc...
5,I was really disappointed after viewing Pinocc...,I was really disappointed after viewing Pinocc...,1,0,oldest,youngest,I was really disappointed after viewing Pinocc...,I was really disappointed after viewing Pinocc...
6,The Man From Utah opens with a singing cowboy ...,The Man From Utah opens with a singing cowboy ...,0,1,old,young,The Man From Utah opens with a singing cowboy ...,The Man From Utah opens with a singing cowboy ...
7,This appears to be one of Noel Coward's lesser...,This appears to be one of Noel Coward's lesser...,0,1,old,young,This appears to be one of Noel Coward's lesser...,This appears to be one of Noel Coward's lesser...
8,This movie has been a classic in my part of th...,This movie has been a classic in my part of th...,0,1,older,younger,This movie has been a classic in my part of th...,This movie has been a classic in my part of th...
9,This movie has been a classic in my part of th...,This movie has been a classic in my part of th...,0,1,oldest,youngest,This movie has been a classic in my part of th...,This movie has been a classic in my part of th...
10,"This series, while idealized and fictionalized...","This series, while idealized and fictionalized...",0,1,older,younger,"This series, while idealized and fictionalized...","This series, while idealized and fictionalized..."

In [317]:
print("Number of BTC: ", int(len(btc)))

Number of BTC:  11

In [318]:
btc = btc.sample(frac=1, random_state=123)

texts = []
templates = []
for index, rows in btc.iterrows():
    texts.append(rows["original"])
    texts.append(rows["mutant_1"])
    texts.append(rows["mutant_2"])
    templates.append(rows["template"])

In [319]:
# texts

In [320]:
user_study = pd.DataFrame(data={"text":texts})
template = pd.DataFrame(data={"template":templates})

In [321]:
user_study

                                                 text
0   Bud Abbott and Lou Costello always had a good ...
1   Bud Abbott and Lou Costello always had a good ...
2   Bud Abbott and Lou Costello always had a good ...
3   I was really disappointed after viewing Pinocc...
4   I was really disappointed after viewing Pinocc...
5   I was really disappointed after viewing Pinocc...
6   I was really disappointed after viewing Pinocc...
7   I was really disappointed after viewing Pinocc...
8   I was really disappointed after viewing Pinocc...
9   This appears to be one of Noel Coward's lesser...
10  This appears to be one of Noel Coward's lesser...
11  This appears to be one of Noel Coward's lesser...
12  This movie has been a classic in my part of th...
13  This movie has been a classic in my part of th...
14  This movie has been a classic in my part of th...
15  This movie has been a classic in my part of th...
16  This movie has been a classic in my part of th...
17  This movie has been a classic in my part of th...
18  Hitchcock once gave an interview where he said...
19  Hitchcock once gave an interview where he said...
20  Hitchcock once gave an interview where he said...
21  Bud Abbott and Lou Costello always had a good ...
22  Bud Abbott and Lou Costello always had a good ...
23  Bud Abbott and Lou Costello always had a good ...
24  The Man From Utah opens with a singing cowboy ...
25  The Man From Utah opens with a singing cowboy ...
26  The Man From Utah opens with a singing cowboy ...
27  This series, while idealized and fictionalized...
28  This series, while idealized and fictionalized...
29  This series, while idealized and fictionalized...
30  Hitchcock once gave an interview where he said...
31  Hitchcock once gave an interview where he said...
32  Hitchcock once gave an interview where he said...

In [322]:
user_study.to_csv("user_study_age.csv")
template.to_csv("template_age.csv")