In [1]:
import pandas as pd
import numpy as np
import math
import spacy

from utils import preprocessText
from MutantGeneration import MutantGeneration

In [3]:
df = pd.read_csv("../../data/imdb/test.csv", names=["label", "sentence"], sep="\t")
df

       label                                           sentence
0          1  The Mascot is Ladislaw Starewicz's masterpiece...
1          1  this is one of the finest movies i have ever s...
2          1  I have only see three episodes of Hack, starri...
3          1  Deepa Mehta's "Fire" is groundbreaking, bold, ...
4          0  Anyone who sees this film will notice that the...
...      ...                                                ...
24995      1  How do you describe perfection? In-the-Mood-Fo...
24996      1  The French Babbette appears at the modest hous...
24997      0  The first half of this film held some promise ...
24998      0  I watched "Fuckland" a long time ago. I lied i...
24999      1  First, I'm a huge Buddy Holly fan. I grew up k...

[25000 rows x 2 columns]

In [4]:
import time
start = time.time()

originals = []
templates = []
mutants = []
labels = []
identifiers = []
types = []
genders = []
countries = []

i = 0
counter = 0
for index, row in df.iterrows():
    label = row["label"]
    text = row["sentence"]
    text = preprocessText(text)
    mg = MutantGeneration(text)
    i += 1
    if i%200 == 0 : print(i)
            
    if len(mg.getMutants()) > 0:    
        originals.extend([text] * len(mg.getMutants()))
        labels.extend([label] * len(mg.getMutants()))
        templates.extend(mg.getTemplates())
        mutants.extend(mg.getMutants())
        genders.extend(mg.getGenders())

end = time.time()
print("Execution Time: ", end-start)

200

KeyboardInterrupt:

In [6]:
print(text)

First, I'm a huge Buddy Holly fan. I grew up knowing who he was, and I knew all about that fateful plane ride that extinguished three incredibly bright flames just like that. But I had never truly listened to his music. I had heard much of it, yes, but not until I sat down with the intention of getting something out of it did I truly come to see the real Buddy Holly. And let me tell you that my world is a different one now because of him. Because of this adoration for such an incredible man, I bought The Buddy Holly Story without ever seeing it previously. I'm torn on my views of this film. Perhaps it's because Buddy feels so alive to me that I just couldn't bear seeing Gary Busey in this role. I'll admit that he did a nice job acting, but his singing sounded so forced. It seemed to me as if he knew he didn't sound a bit like Buddy himself and therefore was using far too much energy to make an attempt at a similar sound. In some parts of the film, he succeeded. But others .. ouch. The movie spanned a period of several years, but I feel that portraying this time span could have been handled much better. I had a difficult time distinguishing at what point in Buddy's life certain events were happening. I also had a serious problem with some of the historical inaccuracies. I think the worst one was the portrayal of the Crickets. I understand how their real names couldn't be used, and how for simplification there were only two of them in the movie .. and maybe this was a good thing. Because the film's background vocals were cringeworthy, and I disliked the way they were portrayed as a hindrance to Buddy's career. Something else that really made no difference to the film but irked me was Gary Busey's teeth. They wore me out! Buddy Holly had much better teeth. I don't know why I noticed it .. but I did. I'll end this review on what I felt was the best part of the movie: Buddy's last performance. His final phone call to Maria, the Big Bopper's performance, bringing him and Richie Valens to the stage, followed by the still frame ending. It startled even me, and I feel that it effectively shows the audience how at one moment Buddy Holly was so alive and energetic, and that his flame was snuffed out in the blink of an eye. It was a beautiful way to portray this horrible tragedy I think. Good movie, despite the obvious problems .. 7/10. Some obvious flaws, could use some work ... but not bad.

In [7]:
print(len(originals))
print(len(labels))
print(len(templates))
print(len(templates))
print(len(mutants))
print(len(genders))

1395616
1395616
1395616
1395616
1395616
1395616

In [38]:
dm = pd.DataFrame(data={"label": labels, "mutant": mutants, "template": templates, "original": originals, "gender": genders})
dm

,label,mutant,template,original,gender
0,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",male
1,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",male
2,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",male
3,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",male
4,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",male
...,...,...,...,...,...
1395611,1,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,female
1395612,1,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,female
1395613,1,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,female
1395614,1,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,female
1395615,1,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,female

In [36]:
dm = dm.drop_duplicates().reset_index(drop=True)
dm

,label,mutant,template,original,gender,template_id
0,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",male,3736
1,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",male,3736
2,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",male,3736
3,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",male,3736
4,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",male,3736
...,...,...,...,...,...,...
214669,1,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,female,9059
214670,1,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,female,9059
214671,1,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,female,9059
214672,1,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,female,9059
214673,1,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,female,9059

In [39]:
dm["template"] = dm["template"].astype("category")
dm["template_id"] = dm["template"].cat.codes

In [40]:
gb = dm.groupby("template_id")
gb.count()

             label  mutant  template  original  gender
template_id
0               20      20        20        20      20
1               26      26        26        26      26
2                2       2         2         2       2
3               20      20        20        20      20
4               20      20        20        20      20
...            ...     ...       ...       ...     ...
11098           20      20        20        20      20
11099            2       2         2         2       2
11100           20      20        20        20      20
11101           20      20        20        20      20
11102           20      20        20        20      20

[11103 rows x 5 columns]

In [35]:
dm.to_csv("../../data/gc_imdb/test.csv", index=None, header=None, sep="\t")

In [15]:
gb.count().sort_values(by=["label"])

              label  mutant  template  original  gender
template_id
4521              2       2         2         2       2
6999              2       2         2         2       2
1985              2       2         2         2       2
9163              2       2         2         2       2
1989              2       2         2         2       2
...             ...     ...       ...       ...     ...
4517          57122   57122     57122     57122   57122
1443          57122   57122     57122     57122   57122
5721          57122   57122     57122     57122   57122
839           57122   57122     57122     57122   57122
10936        742586  742586    742586    742586  742586

[11103 rows x 5 columns]

In [42]:
gb.get_group(10936)["original"][92974]

"i guess if they are not brother this film will became very common. how long were they can keep this? if we were part, what should they do?so natural feelings, so plain and barren words. But I almost cried last night blood relationship brotherhood love knot film.in another word, the elder brother is very cute.if they are not brothers, they won't have so many forbidden factorsfrom the familysocietyfriendseven hearts of their own at the very beginning. The elder brother is doubtful of whether he is coming out or not at the beginning .maybe the little brother being so long time with his brother and even can't got any praise from his fatherthis made him very upset and even sad, maybe this is a key blasting fuse let him feel there were no one in the world loving him except his beloved brother. and i want to say, this is a so humannatural feeling, there is nothing to be shamed, you may fell in love your motherbrothersister. Just a frail heart looking for backbone to rely on"

In [21]:
dm = dm.drop_duplicates().reset_index(drop=True)
dm

,label,mutant,template,original,gender,template_id
0,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",male,3736
1,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",male,3736
2,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",male,3736
3,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",male,3736
4,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",male,3736
...,...,...,...,...,...,...
214669,1,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,female,9059
214670,1,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,female,9059
214671,1,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,female,9059
214672,1,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,female,9059
214673,1,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,This is another of my favorite Columbos. It sp...,female,9059

In [22]:
dm.groupby("template_id").count().sort_values(by=["label"])

             label  mutant  template  original  gender
template_id
8414             2       2         2         2       2
2882             2       2         2         2       2
2887             2       2         2         2       2
2888             2       2         2         2       2
2889             2       2         2         2       2
...            ...     ...       ...       ...     ...
854            240     240       240       240     240
2604           240     240       240       240     240
6455           240     240       240       240     240
478            240     240       240       240     240
10363          240     240       240       240     240

[11103 rows x 5 columns]

In [49]:
dm.groupby("template_id").get_group(478)["original"][89058]

'Larry is a perfect example of the Democratic Party in the United States, of which he is a staunch member. King used to be somewhat fair and unbiased and had a variety of guests on. The Party used to be centrist, too, but that was another era. Now, like, Larry, it\'s Far Left.   At least 90 percent of all the guests on King\'s show in the past year or two are Liberals who sit there and bash President Bush and every Conservative they can think of ..... night after night. Bill Mahar, one of the more viscous ones, isand you can look this upthe most frequent guest in the history of King\'s TV show. You can count on other outspoken Left Wingers to be on King\'s show each week, but don\'t hold your breath waiting for a Conservative. They are few and far between. King was also one of the innovators of the media overkill. That all began with the O.J. Simpson trial. Night after night after night that\'s all you ever saw back in the mid \' 90s. Whatever latest gossip on Anna Nicole Smith, or the Petersen murder case, or Paris Hilton, Britney Spears or some other tabloid subject, you can bet Larry will beat it to death. Sadly, all the other networks do the same thing now. Larry was a leader in that regard. King also has the nerve to sometimes give advice, such as on marriage. I am not kidding; I \' ve heard him say it. The joke is that he has been married and divorced a half dozen times! This man has few scruples, believe me. When it comes to morality, he is clueless. Maybe that\'s why he has Dr. Phil on, to explain some facts of life to him regularly. Larry will nod, but he doesn\'t understand any more than when Billy Graham used to talk to him. King also is becoming famous for the " softball " interview, meaning he asks no hard questions. That is a lot due to the fact that most his guests are of his political persuasion. People know being on King\'s show is liking having an hour public relations gig. What all this has meant is a serious decline in ratings the past five years. People see through him and his LiberalandtabloidTV mentality and switched over from King and CNN to Fox News.'

In [24]:
dm.groupby("template_id").get_group(10363)["template"]

'What exactly is the point of pretending to " con " people out of things like ski passes and pizza? I fail to see a point. I\'d not clever or original and it strikes me as being extremely pointless. <name> doesn\'t seem to be a very downtoearth or even a nice guy. <pro-He> has very little charisma and just about anyone could do what <pro-he> does in this show. The worse thing about this piece of crap, is the fact that a lot of the phone calls are reenacted, so not only are they apparently conning the poor people on the other end of the phone, but they are also conning the audience who don\'t have enough time to read the " disclaimed " that flickers across the screen for about half a second at the beginning at the end of the show! Not only that but <pro-he> also claims this is how <pro-he> lives <pro-his> whole life. What an lie. No one could live their lives like this and the fact <pro-he> says this is not only yet another con to get <pro-his> show watched, but it\'s also one of the most fabricated, blatant pieces of bull$hit I\'ve ever heard. This <gaw> is an @$$! What makes them think that going to all the trouble of, for example, write and record a song, get someone to pain a HUGE picture of you and two mates, get dance lessons and actually travel to a ski resort is actually worth only getting free ski passes and some food for free? What is the point of that? It\'s an awful lot of trouble to go to just for a few ski passes and a bit of snow. As far as " comedy " goes, this is bottom of the barrel stuff.'

In [45]:
dm.groupby("template_id").get_group(839)["original"][14018]

'A fascinating slice of life documentary about a husband and wife and their marriage told through the eyes of their son. We all like to think that our parents lived happy lives, that their marriages were full of fulfilment, love, and happy memories. Sadly many of us know this not to be the case of their own families and that of their parents. This wonderful little documentary is told through the camera lens and emotional perspective of the son of a family that has just experienced the death of their mother. The son being a documentary film maker has filmed his elder family for many years, for as he states " posterity ". Three months after the death of his mother his father remarries his long time secretary. The suddenness of this occurrence stuns the family and pushes the son to dig into the past lives of his mother and father. What he reveals is a fascinating look into the lives of two rather ordinary people who like so many of their generation married early for the wrong reasons and found themselves stuck in a family life where they found they just had to " make do ". A wife who found herself at times bitterly lonely and unloved and a husband who buries himself in his work. She and intellectual at heart, he a much simpler individual who seems to find most of his pleasures in the quiet solitude of work. They are obviously wrong for each other, this much is clear. Yet they stick it out, for what? Well that\'s part of the mystery, they clearly show affection for each other at times if not ever much love. You won\'t find any truly shocking disclosures here, aside from infidelity on both sides, which in good part is what makes this such a gem. You really feel that these could be your own parents if circumstances were different and indeed makes one question the lives of ones own parents.'

In [362]:
import os

dirname = "../data/gc_imdb/"
# dirname = "../data/imdb_using_eec_name/"

if not os.path.exists(dirname) :
    os.makedirs(dirname)

dmutant.to_csv(dirname + "test.csv", index=None, header=None, sep="\t")

dmutant_shuffled = dmutant.sample(frac=1, random_state=123).reset_index(drop=True)
dmutant_shuffled.to_csv(dirname + "train.csv", index=None, header=None, sep="\t")

In [310]:
dmutant

,label,mutant,template,original,identifier,type,gender,country
0,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Alonzo,name,male,African American
1,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Adam,name,male,African American
2,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Alphonse,name,male,African American
3,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Alan,name,male,African American
4,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Darnell,name,male,African American
...,...,...,...,...,...,...,...,...
140837,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Melanie,name,female,European American
140838,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Tanisha,name,female,European American
140839,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Nancy,name,female,European American
140840,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Tia,name,female,European American
140841,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Stephanie,name,female,European American

In [2]:
import pandas as pd

# dirname = "../data/gc_imdb/"
dirname = "../data/imdb_using_eec_name/"
dmutant = pd.read_csv(dirname + "test.csv", sep="\t", names=["label", "mutant", "template", "original", "identifier", "type", "gender", "country"])

In [3]:
dmutant

,label,mutant,template,original,identifier,type,gender,country
0,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Alonzo,name,male,African American
1,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Adam,name,male,African American
2,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Alphonse,name,male,African American
3,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Alan,name,male,African American
4,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Darnell,name,male,African American
...,...,...,...,...,...,...,...,...
140837,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Melanie,name,female,European American
140838,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Tanisha,name,female,European American
140839,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Nancy,name,female,European American
140840,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Tia,name,female,European American
140841,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Stephanie,name,female,European American

In [4]:
dmutant["template"] = dmutant["template"].astype("category")
dmutant["template_id"] = dmutant["template"].cat.codes

In [5]:
dmutant

,label,mutant,template,original,identifier,type,gender,country,template_id
0,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Alonzo,name,male,African American,1218
1,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Adam,name,male,African American,1218
2,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Alphonse,name,male,African American,1218
3,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Alan,name,male,African American,1218
4,1,"I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...","I have only see three episodes of Hack, starri...",Darnell,name,male,African American,1218
...,...,...,...,...,...,...,...,...,...
140837,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Melanie,name,female,European American,3417
140838,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Tanisha,name,female,European American,3417
140839,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Nancy,name,female,European American,3417
140840,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Tia,name,female,European American,3417
140841,1,"Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...","Well, the movie did turn out a lot better than...",Stephanie,name,female,European American,3417

In [6]:
dmutant.groupby("template_id").count()

,label,mutant,template,original,identifier,type,gender,country
template_id,,,,,,,,
0,40,40,40,40,40,40,40,40
1,26,26,26,26,26,26,26,0
2,40,40,40,40,40,40,40,40
3,40,40,40,40,40,40,40,40
4,40,40,40,40,40,40,40,40
...,...,...,...,...,...,...,...,...
3725,40,40,40,40,40,40,40,40
3726,40,40,40,40,40,40,40,40
3727,40,40,40,40,40,40,40,40
3728,26,26,26,26,26,26,26,0
3729,40,40,40,40,40,40,40,40

In [7]:
dmutant.groupby("type").count()

,label,mutant,template,original,identifier,gender,country,template_id
type,,,,,,,,
gaw,15158,15158,15158,15158,15158,15158,0,15158
name,121880,121880,121880,121880,121880,121880,121880,121880
person-pronoun-gaw,364,364,364,364,364,364,0,364
person-pronoun-name,920,920,920,920,920,920,920,920
person-pronoun-sltn,40,40,40,40,40,40,40,40
sltn,2480,2480,2480,2480,2480,2480,2480,2480

In [8]:
NAME = "name"
SALUTATION = "sltn"
GAW = "gaw"
P = "person-pronoun-"
PNAME = P + NAME
PGAW = P + GAW
PSALUTATION = P + SALUTATION

In [43]:
name = dmutant.groupby("type").get_group(NAME)

In [44]:
name = name.iloc[:,[2,3]]

In [46]:
name = name.drop_duplicates().reset_index(drop=True)

In [139]:
id = 49
id = 62
id = 72
id = 78
id = 81
id = 83
name["template"][id]

"According to me, a movie can be best rated by the number of ' best scenes ' there are. There are probably at least 8090 scenes in the whole movie that is probably rated as ' best ' by somebody or the other. This movie is a masterpiece. Period. I know many who have called it ahead of its time, probably because it bombed at boxoffice. However, I think any generation can relate to this movie and have a good laugh through out. I am personally glad that <name> is part of the movie too. <pro-His> role isn't that ' meaty ', however its good to see that <pro-he> is a part of the cast in the funniest Hindi movie ever."

In [140]:
name["original"][id]

"According to me, a movie can be best rated by the number of ' best scenes ' there are. There are probably at least 8090 scenes in the whole movie that is probably rated as ' best ' by somebody or the other. This movie is a masterpiece. Period. I know many who have called it ahead of its time, probably because it bombed at boxoffice. However, I think any generation can relate to this movie and have a good laugh through out. I am personally glad that Mahmood is part of the movie too. His role isn't that ' meaty ', however its good to see that he is a part of the cast in the funniest Hindi movie ever."

In [39]:
id = 0
print(dmutant.groupby("type").get_group(NAME).iloc[id]["original"])
print()
print(dmutant.groupby("type").get_group(NAME).iloc[id]["template"])

I have only see three episodes of Hack, starring David Morse, and it looks as though I've missed 37 episodes! well that s if ITV 3 are showing them in chronological order. I've just watched ' Misty Blue ' ( episode 38). I have really enjoyed the 3 episodes, but then I'm a David Morse fan, ( esp St. Elsewhere). For any one reading this, Hack is excellent. Pity its being aired on ITV 3. The cast is strong, though I ca nt get used to the idea of David playing a bent cop, still we all know he's the good guy wrongly accused. I see Gary Cole has guest starred, what ever happened to ' Midnight Caller '? Just wonder if Hack is available on DVD ( yet). Lovin it. Cheers.

I have only see three episodes of Hack, starring David Morse, and it looks as though I've missed 37 episodes! well that s if ITV 3 are showing them in chronological order. I've just watched ' Misty Blue ' ( episode 38). I have really enjoyed the 3 episodes, but then I'm a David Morse fan, ( esp St. Elsewhere). For any one reading this, Hack is excellent. Pity its being aired on ITV 3. The cast is strong, though I ca nt get used to the idea of <name> playing a bent cop, still we all know <pro-he> 's the good guy wrongly accused. I see Gary Cole has guest starred, what ever happened to ' Midnight Caller '? Just wonder if Hack is available on DVD ( yet). Lovin it. Cheers.

In [37]:
id = 520
print(dmutant.groupby("type").get_group(NAME).iloc[id]["original"])
print()
print(dmutant.groupby("type").get_group(NAME).iloc[id]["template"])

Just when you think that you've seen the worst the zombie subgenre can offer, along comes another budding Romero and his team of notalent mates to prove you wrong. I've suffered the Zombie Bloodbath trilogy, endured Death Valley: The Revenge of Bloody Bill, sat semicomatose through The Zombie Diaries, and laughed hysterically during Zombie ' 90: Extreme Pestilence, and genuinely thought that amateur moviemaking could sink no lower. However, having just watched Zombie Planet, a two hour long festering pile of drivel from writer/ director George Bonilla, I think I have found the ultimate in awful zombie movies. In this dreadfully amateurish effort, which is part Mad Max and part Dawn of the Dead ( but ALL bad), Frank Farhat stars as T. K. Kane, a tough fighter who kicks zombie ass for a hobby, armed only with knives, a machete, some concussion grenades, and what he obviously perceives to be a really mean glare. After a desperately unexciting opening sequence in which he takes on a horde of dodgy looking zombies, Kane teams up with a group of survivors who not only have to fend off attacks from the undead, but must also must placate a gang of vicious thugs who have taken control of the area ( by searching for and handing over any valuables that they find). Of course, Kane isn't the type of man to take orders from a bunch of zgrade postapocalyptic bully boys, and he sets about teaching the bad guys a lesson ( mostly by glowering at them in a threatening manner), only pausing to periodically rescue pals from zombies. Featuring awful acting from almost everyone involved, a dreadful script, laughable effects, and shoddy production values, there is virtually nothing in this film to make it worth a watch. To be fair, I quite like the basic premise that the zombies are the unexpected result of a highly popular slimming drug that blocks cravings for carbohydrates ( we learn this when one character conveniently explains the backstory to Kane, who strangely has no idea what has happened), but this is about the only vaguely interesting aspect of the whole production. I have a certain amount of respect for anyone who manages to fund and make their own movie, but when the results are this poor, that respect is lost when they decide to make it available for public viewing. I would've kept this one under wraps if I had made it.

Just when you think that you've seen the worst the zombie subgenre can offer, along comes another budding Romero and his team of notalent mates to prove you wrong. I've suffered the Zombie Bloodbath trilogy, endured Death Valley: The Revenge of Bloody Bill, sat semicomatose through The Zombie Diaries, and laughed hysterically during Zombie ' 90: Extreme Pestilence, and genuinely thought that amateur moviemaking could sink no lower. However, having just watched Zombie Planet, a two hour long festering pile of drivel from writer/ director George Bonilla, I think I have found the ultimate in awful zombie movies. In this dreadfully amateurish effort, which is part Mad Max and part Dawn of the Dead ( but ALL bad), <name> stars as T. K. Kane, a tough fighter who kicks zombie ass for a hobby, armed only with knives, a machete, some concussion grenades, and what <pro-he> obviously perceives to be a really mean glare. After a desperately unexciting opening sequence in which <pro-he> takes on a horde of dodgy looking zombies, <name> teams up with a group of survivors who not only have to fend off attacks from the undead, but must also must placate a gang of vicious thugs who have taken control of the area ( by searching for and handing over any valuables that they find). Of course, <name> isn't the type of man to take orders from a bunch of zgrade postapocalyptic bully boys, and <pro-he> sets about teaching the bad guys a lesson ( mostly by glowering at them in a threatening manner), only pausing to periodically rescue pals from zombies. Featuring awful acting from almost everyone involved, a dreadful script, laughable effects, and shoddy production values, there is virtually nothing in this film to make it worth a watch. To be fair, I quite like the basic premise that the zombies are the unexpected result of a highly popular slimming drug that blocks cravings for carbohydrates ( we learn this when one character conveniently explains the backstory to Kane, who strangely has no idea what has happened), but this is about the only vaguely interesting aspect of the whole production. I have a certain amount of respect for anyone who manages to fund and make their own movie, but when the results are this poor, that respect is lost when they decide to make it available for public viewing. I would've kept this one under wraps if I had made it.

In [14]:
id = 9000
print(dmutant.groupby("type").get_group(NAME).iloc[id]["original"])
print()
print(dmutant.groupby("type").get_group(NAME).iloc[id]["template"])

How truly sad that this sprung from the same mind as Donnie Darko, possibly one of the best films in this genre. Where do I even begin? I think one of the must infuriating aspects of the film is that we are supposed to be critiquing humanity, and yet we see no humanity in the film. No more than 5 minutes of the film is spend agonizing about the possible death of another human. These are horrible one dimensional cardboard cutouts of human beings. Sadly, that's how they are played with what can only be described as dreadful acting. Is this truly how Kelly sees humanity? Judging from the reaction of viewers, this is a horrible encapsulation of humanity. Why don't the characters in the film ask the questions that all the viewers have? This is not an indictment of humanity. It's an indictment of the straw men that Kelly sets up who bare almost no resemblance to real humans in this situation. To those who say this was a wonderful thoughtprovoking film, to what are you comparing it? Armageddon? I even saw someone compare this to the works of Kurosawa. How truly deprived must you be to think that this would promote good existential discussion? For the love of all that's good in film! Even Indecent Proposal is ten times the indictment of humanity that this is. There we see people truly agonizing about greed and the human condition. Yes, even Indecent Proposal puts this film to shame for philosophical discussion and yet it gets 5.3 vs 6.0 for this mindless tripe. Rarely have I seen a more pretentious, pontificating, and self aggrandizing, film fall so flatly on its face. This has the depth of a high school film project, and a poor one at that. Truly, that's about the level of the discussion promoted by this film. If you want to see GOOD psychological film making, do yourself a favor and check out Das Experiment. If The Box had lived up even to this one goal, I would have been willing to forgive some of the atrocious acting, gaping plot holes, and sheer nonsensical storyline. Sadly, it can't even do that. The true indictment of humanity is that there are people out there who think this film is a deeply delving introspective look into the human condition. This is not Sartre! This is not even the Cliff Notes version of Sartre! This is a hastily conceived and hackwritten 9th grade term paper on Sartre based on some internet message board ramblings. If Sartre were alive, he would sue Kelly for defamation.

How truly sad that this sprung from the same mind as Donnie Darko, possibly one of the best films in this genre. Where do I even begin? I think one of the must infuriating aspects of the film is that we are supposed to be critiquing humanity, and yet we see no humanity in the film. No more than 5 minutes of the film is spend agonizing about the possible death of another human. These are horrible one dimensional cardboard cutouts of human beings. Sadly, that's how they are played with what can only be described as dreadful acting. Is this truly how Kelly sees humanity? Judging from the reaction of viewers, this is a horrible encapsulation of humanity. Why don't the characters in the film ask the questions that all the viewers have? This is not an indictment of humanity. It's an indictment of the straw men that Kelly sets up who bare almost no resemblance to real humans in this situation. To those who say this was a wonderful thoughtprovoking film, to what are you comparing it? Armageddon? I even saw someone compare this to the works of Kurosawa. How truly deprived must you be to think that this would promote good existential discussion? For the love of all that's good in film! Even Indecent Proposal is ten times the indictment of humanity that this is. There we see people truly agonizing about greed and the human condition. Yes, even Indecent Proposal puts this film to shame for philosophical discussion and yet it gets 5.3 vs 6.0 for this mindless tripe. Rarely have I seen a more pretentious, pontificating, and self aggrandizing, film fall so flatly on its face. This has the depth of a high school film project, and a poor one at that. Truly, that's about the level of the discussion promoted by this film. If you want to see GOOD psychological film making, do yourself a favor and check out Das Experiment. If The Box had lived up even to this one goal, I would have been willing to forgive some of the atrocious acting, gaping plot holes, and sheer nonsensical storyline. Sadly, it can't even do that. The true indictment of humanity is that there are people out there who think this film is a deeply delving introspective look into the human condition. This is not <name> ! This is not even the Cliff Notes version of <name> ! This is a hastily conceived and hackwritten 9th grade term paper on <name> based on some internet message board ramblings. If <name> were alive, <pro-he> would sue Kelly for defamation.

In [173]:
dmutant.groupby("type").get_group(SALUTATION)

,label,mutant,template,original,identifier,type,gender,country,template_id
29324,0,"The James Dean Story is introduced as "" A diff...","The James Dean Story is introduced as "" A diff...","The James Dean Story is introduced as "" A diff...",Roen,sltn,male,UK,2526
29325,0,"The James Dean Story is introduced as "" A diff...","The James Dean Story is introduced as "" A diff...","The James Dean Story is introduced as "" A diff...",Jeet,sltn,male,UK,2526
29326,0,"The James Dean Story is introduced as "" A diff...","The James Dean Story is introduced as "" A diff...","The James Dean Story is introduced as "" A diff...",Hagen,sltn,male,UK,2526
29327,0,"The James Dean Story is introduced as "" A diff...","The James Dean Story is introduced as "" A diff...","The James Dean Story is introduced as "" A diff...",Willow,sltn,male,UK,2526
29328,0,"The James Dean Story is introduced as "" A diff...","The James Dean Story is introduced as "" A diff...","The James Dean Story is introduced as "" A diff...",Belal,sltn,male,UK,2526
...,...,...,...,...,...,...,...,...,...
963545,1,"Although it isn't mentioned very often, "" Don'...","Although it isn't mentioned very often, "" Don'...","Although it isn't mentioned very often, "" Don'...",Dódi,sltn,female,Hungary,234
963546,1,"Although it isn't mentioned very often, "" Don'...","Although it isn't mentioned very often, "" Don'...","Although it isn't mentioned very often, "" Don'...",Iboyka,sltn,female,Hungary,234
963547,1,"Although it isn't mentioned very often, "" Don'...","Although it isn't mentioned very often, "" Don'...","Although it isn't mentioned very often, "" Don'...",Zsófia,sltn,female,Hungary,234
963548,1,"Although it isn't mentioned very often, "" Don'...","Although it isn't mentioned very often, "" Don'...","Although it isn't mentioned very often, "" Don'...",Ágota,sltn,female,Hungary,234
963549,1,"Although it isn't mentioned very often, "" Don'...","Although it isn't mentioned very often, "" Don'...","Although it isn't mentioned very often, "" Don'...",Alexa,sltn,female,Hungary,234

In [174]:
id = 0
print(dmutant.groupby("type").get_group(SALUTATION).iloc[id]["original"])
print()
print(dmutant.groupby("type").get_group(SALUTATION).iloc[id]["template"])

The James Dean Story is introduced as " A different kind of motion picture, " explaining, " The presence of the leading character in this film has been made possible by the use of existing motion picture material, tape recordings of his voice and by means of a new techniquedynamic exploration of the still photograph. " The only " tape recordings of his voice " noteworthy is one short recording Mr. Dean make while visiting his family in Indiana; he wanted to record any family recollections of his greatgrandfather Cal Dean, intrigued because he played a similarly named " Cal " in " East of Eden ". Dean asks if Cal Dean was interested in art, and learns the relative was an auctioneer. James Dean was interested in art and had warm relationship with his family, obviously. That's the only 100% accurate revelation in this documentary. James Dean was interested in art and had warm relationship with his family. An amazing " screen test"/"outtake " from " East of Eden " appears near the film's end. It's a black and white scene between Dean ( as Cal Trask) and costar Richard Davalos ( as Aron Trask). Dean is at his mesmerizing best. If this scene appeared only here, and no " East of Eden " film was completed, this documentary would be an essential, high rated film. But the scene, a perfect " 10 " in isolation, should be considered an " East of Eden " extra. Dean's " Traffic Safety Film " is also worth seeing. There are the expected interviews with family and friends. My favorites were the guy ( Lew Bracker) going through a box of stuff Dean left with him, and Dean's family. There wasn't enough from Aunt Ortense and the letter from Dean to his little cousin was very nice. More reading of Dean's letters would have been welcome. Dean's unidentified writer friend seemed to have a better thesis for the film; filmmakers might have considered developing it as a main focus. Robert Altman's direction of Martin Gabel's reading of Stewart Stern's script is dreadful. What were they thinking? Perhaps, filmmakers can be forgiven due to the closeness of Dean's passing. Don't expect " The James Dean Story " at all. This movie is more about Dean's effect on people ( both the fans and filmmakers) than the man. It is very clearly an early piece of the James Dean mythmaking " legend ". Tommy Sands sings " Let Me Be Loved ". The narrative refers to Dean as " He " with a godlike air. The shots of Dean's family seeming to " know " the moment he dies are truly wretched.** The James Dean Story ( 8/13/57) Robert Altman~ James Dean, Martin Gabel, Richard Davalos

The James Dean Story is introduced as " A different kind of motion picture, " explaining, " The presence of the leading character in this film has been made possible by the use of existing motion picture material, tape recordings of his voice and by means of a new techniquedynamic exploration of the still photograph. " The only " tape recordings of his voice " noteworthy is one short recording <sltn-Mr.> <name> make while visiting <pro-his> family in Indiana; <pro-he> wanted to record any family recollections of <pro-his> greatgrandfather Cal Dean, intrigued because <pro-he> played a similarly named " Cal " in " East of Eden ". <sltn-Mr.> <name> asks if <sltn-Mr.> <name> was interested in art, and learns the relative was an auctioneer. <sltn-Mr.> <name> was interested in art and had warm relationship with <pro-his> family, obviously. That's the only 100% accurate revelation in this documentary. <sltn-Mr.> <name> was interested in art and had warm relationship with <pro-his> family. An amazing " screen test"/"outtake " from " East of Eden " appears near the film's end. It's a black and white scene between <sltn-Mr.> <name> ( as Cal Trask) and costar Richard Davalos ( as Aron Trask). <sltn-Mr.> <name> is at <pro-his> mesmerizing best. If this scene appeared only here, and no " East of Eden " film was completed, this documentary would be an essential, high rated film. But the scene, a perfect " 10 " in isolation, should be considered an " East of Eden " extra. <sltn-Mr.> <name> 's " Traffic Safety Film " is also worth seeing. There are the expected interviews with family and friends. My favorites were the guy ( Lew Bracker) going through a box of stuff <sltn-Mr.> <name> left with <pro-him> , and <sltn-Mr.> <name> 's family. There wasn't enough from Aunt Ortense and the letter from <sltn-Mr.> <name> to <pro-his> little cousin was very nice. More reading of <sltn-Mr.> <name> 's letters would have been welcome. <sltn-Mr.> <name> 's unidentified writer friend seemed to have a better thesis for the film; filmmakers might have considered developing it as a main focus. Robert Altman's direction of Martin Gabel's reading of Stewart Stern's script is dreadful. What were they thinking? Perhaps, filmmakers can be forgiven due to the closeness of <sltn-Mr.> <name> 's passing. Don't expect " The James Dean Story " at all. This movie is more about <sltn-Mr.> <name> 's effect on people ( both the fans and filmmakers) than the man. It is very clearly an early piece of the James Dean mythmaking " legend ". Tommy Sands sings " Let Me Be Loved ". The narrative refers to <sltn-Mr.> <name> as " <pro-He> " with a godlike air. The shots of <sltn-Mr.> <name> 's family seeming to " know " the moment <pro-he> dies are truly wretched.** The James Dean Story ( 8/13/57) Robert Altman~ James Dean, Martin Gabel, Richard Davalos

In [175]:
id = 400
print(dmutant.groupby("type").get_group(SALUTATION).iloc[id]["original"])
print()
print(dmutant.groupby("type").get_group(SALUTATION).iloc[id]["template"])

This is one of my favorite T.V shows of all time, Rowan Atkinson is simply a genius!, and it's only fitting that i chose this to be my 1000 review!. I can't begin to tell you how much i love Mr. Bean he's the man, and what amazes me, is how he gets out of these incredibly difficult situations, and he is always so creative, plus Robyn Driscoll also deserves accolades!, he is also a genius!. My favorite bit that he has done is the Amazing Adventures of Mr. Bean and while all the rest of them are amazing, this remains my true favorite, plus i wish the show didn't stop so soon!. Each episode is brilliantly written, and they were all masterfully directed, plus Each episode is a classic in my eyes!. This show is incredibly popular, and i can definitely see why, as it's quite possibly the funniest show ever. The character actors all played there roles really well, especially Robyn Driscoll and Matilda Ziegler ( as Irma). This is one of my favorite T.V shows of all time Rowan Atkinso is simply put a genius and an incredibly talented comedian ( possibly the best!), and it's only fitting that i chose this to be my 1000 review f you haven't seen this show, drop what your doing right now and go check it out, you will not regret it trust me it's one of the best T.V shows ever!,and i will continue to watch the show over and over again, i never tire of it!, Mr. Bean Rules!.***** out of 5

This is one of my favorite T.V shows of all time, Rowan Atkinson is simply a genius!, and it's only fitting that i chose this to be my 1000 review!. I can't begin to tell you how much i love <sltn-Mr.> <name> <pro-he> 's the man, and what amazes me, is how <pro-he> gets out of these incredibly difficult situations, and <pro-he> is always so creative, plus Robyn Driscoll also deserves accolades!, <pro-he> is also a genius!. My favorite bit that <pro-he> has done is the Amazing Adventures of <sltn-Mr.> <name> and while all the rest of them are amazing, this remains my true favorite, plus i wish the show didn't stop so soon!. Each episode is brilliantly written, and they were all masterfully directed, plus Each episode is a classic in my eyes!. This show is incredibly popular, and i can definitely see why, as it's quite possibly the funniest show ever. The character actors all played there roles really well, especially Robyn Driscoll and Matilda Ziegler ( as Irma). This is one of my favorite T.V shows of all time Rowan Atkinso is simply put a genius and an incredibly talented comedian ( possibly the best!), and it's only fitting that i chose this to be my 1000 review f you haven't seen this show, drop what your doing right now and go check it out, you will not regret it trust me it's one of the best T.V shows ever!,and i will continue to watch the show over and over again, i never tire of it!, Mr. Bean Rules!.***** out of 5

In [178]:
id = 1200
print(dmutant.groupby("type").get_group(SALUTATION).iloc[id]["original"])
print()
print(dmutant.groupby("type").get_group(SALUTATION).iloc[id]["template"])

The New Twenty is one of the worst films I have ever seen. Yes, some may argue that formulaic small budget films that strive for less may seem worse, but I would argue that a pseudointellectual antiformulaic " indie " film that pretends to be more is worse.   " The New Twenty " was written and directed by Chris Mason Johnson, and I will never get back the 91 minutes of my life that I wasted on his film. THE SCREENPLAY & CHARACTERS From beginning to end, the screenplay failed to provide an antihero or hero with a moral core that the audience would want to see succeed or fail.   In story telling, the three dramatic conflicts are man vs. man, man vs. the world, and man vs. himself.   The screenplay focuses on a group of college friends in New York, and is preoccupied with the dynamic of man vs. himself, where each of the film's characters are so selfabsorbed in a stupor of depression and selfdestructive behavior that the movie atrophies before the audiences very eyes.   Each of the main characters indulge in unexplained bad behavior ( heroin addiction with no history as to why the character is an addict; a fiance who has sex with her fiance's boss/ investor, even though the character is written too smart to have sex with such a sleazy character; a man who begins as a decent guy, but is attracted to a foulmouthed investor, and converts for some unknown reason into a similar foulmouthed business jackass; a closeted chubby gay cyber geek, who does nothing, but find dates online; and a gay Asian man who dates an HIV positive older man, but has no scenes establishing why the relationship works and why love develops). Crucial scenes establishing the cause of the character's addiction, the suffering and self- loathing of the fiance that might explain why she would sleep with a sleaze bag; the back story that would explain why a decent guy would be attracted to a " Gordon Gecko " type character and become a jackass; a story line for the chubby cyber geek; and more scenes of interaction between the Asian man and HIV positive boyfriend are all missing. Without proper establishing details, all of the characters ' actions seem forced and contrived. DIRECTION, CINEMATOGRAPHY & SCORE I found Mr. Johnson's direction to be without a clear point of view, leaving the actors emotionally incoherent.   The cinematography can be described as mundane at best. Mr. Johnson selected small spaces to shoot and failed to catch the grandeur of New York City. This failure created a claustrophobic film, that viewed like the filming of a stage play, and not a film. The score was embarrassingly absent from most of the film. I assume that Mr. Johnson is to blame, since he could have asked for full score to enhance understanding in each shot. CONCLUSION " The New Twenty " is an annoying and unmitigated failure in filmmaking.

The New Twenty is one of the worst films I have ever seen. Yes, some may argue that formulaic small budget films that strive for less may seem worse, but I would argue that a pseudointellectual antiformulaic " indie " film that pretends to be more is worse. " The New Twenty " was written and directed by Chris Mason Johnson, and I will never get back the 91 minutes of my life that I wasted on his film. THE SCREENPLAY & CHARACTERS From beginning to end, the screenplay failed to provide an antihero or hero with a moral core that the audience would want to see succeed or fail. In story telling, the three dramatic conflicts are man vs. man, man vs. the world, and man vs. himself. The screenplay focuses on a group of college friends in New York, and is preoccupied with the dynamic of man vs. himself, where each of the film's characters are so selfabsorbed in a stupor of depression and selfdestructive behavior that the movie atrophies before the audiences very eyes. Each of the main characters indulge in unexplained bad behavior ( heroin addiction with no history as to why the character is an addict; a fiance who has sex with her fiance's boss/ investor, even though the character is written too smart to have sex with such a sleazy character; a man who begins as a decent guy, but is attracted to a foulmouthed investor, and converts for some unknown reason into a similar foulmouthed business jackass; a closeted chubby gay cyber geek, who does nothing, but find dates online; and a gay Asian man who dates an HIV positive older man, but has no scenes establishing why the relationship works and why love develops). Crucial scenes establishing the cause of the character's addiction, the suffering and self- loathing of the fiance that might explain why she would sleep with a sleaze bag; the back story that would explain why a decent guy would be attracted to a " Gordon Gecko " type character and become a jackass; a story line for the chubby cyber geek; and more scenes of interaction between the Asian man and HIV positive boyfriend are all missing. Without proper establishing details, all of the characters ' actions seem forced and contrived. DIRECTION, CINEMATOGRAPHY & SCORE I found <sltn-Mr.> <name> 's direction to be without a clear point of view, leaving the actors emotionally incoherent. The cinematography can be described as mundane at best. <sltn-Mr.> <name> selected small spaces to shoot and failed to catch the grandeur of New York City. This failure created a claustrophobic film, that viewed like the filming of a stage play, and not a film. The score was embarrassingly absent from most of the film. I assume that <sltn-Mr.> <name> is to blame, since <pro-he> could have asked for full score to enhance understanding in each shot. CONCLUSION " The New Twenty " is an annoying and unmitigated failure in filmmaking.

In [179]:
id = 1600
print(dmutant.groupby("type").get_group(SALUTATION).iloc[id]["original"])
print()
print(dmutant.groupby("type").get_group(SALUTATION).iloc[id]["template"])

I have read almost all the books by now, and have seen the musical production in two different languages. I absolutely adored everything that I have been acquainted previously. But lately I've been running out of resources to sustain my fancy. I still have couple of books left, but they are either in transit or they are the sequels which I am not in a hurry to read. So an idea dawned on meSink me! There are movies which I have not watched! Thus, I must watch them immediately. The first five minutes of these series were ... acceptable. In fact, I quite enjoyed the variation of the reason for the denunciation, however different it had seemed. It went all downhill from there, though. Chauvelin was too ... foppish? And, I daresay, too old for this role. Not nearly that dark and dashing figure with his dreadful eitheror. ( And what was that with random bed scene featuring him? It was way too creepywasn't his only love the Madame Guillotine, and his only interesthis job, and his only obsessionSir Percy?) Marguerite ... Prettiest woman in France? Cleverest woman in Europe? I think not. Although, whatever compelled her to break into the study of Sir Percy I haven't the faintest idea. And whatever my Lord Tony has done to deserve this death? Yes, every member of the League did pledge his life to Sir Percy, but he would have never endangered any of them nor would have run away like a coward when his dear friend faces mortal danger. And if by any means he had to mourn his companion, he would have done that, mourn, not just move on as if nothing had happened. Which brings me to another point, Sir Percy. His portrayal was most dreadful. He was neither a lazy fop, nor a gallant and elusive hero who is a master of transformations. Nor did he care too much about cravats ( his pronunciation of that word alone made my ears bleed) And with his own hands he had never killed anyone. So what was that with him randomly walking around and slaughtering people? The costumes were just too flashy for that time period as well. This is postrevolutionary France we are talking about! Not prerevolutionary. People in dresses like that stand out in a crowd quite easily. It was all just ... gah! Although, I must admit, after I watched other parts my opinion did change slightly. Watching it as a separate work, independent of Scarlet Pimpernel series, it was tolerable. Just your other average hero in the mask. But for what they tried to pass it, it is still miserable.

I have read almost all the books by now, and have seen the musical production in two different languages. I absolutely adored everything that I have been acquainted previously. But lately I've been running out of resources to sustain my fancy. I still have couple of books left, but they are either in transit or they are the sequels which I am not in a hurry to read. So an idea dawned on meSink me! There are movies which I have not watched! Thus, I must watch them immediately. The first five minutes of these series were ... acceptable. In fact, I quite enjoyed the variation of the reason for the denunciation, however different it had seemed. It went all downhill from there, though. Chauvelin was too ... foppish? And, I daresay, too old for this role. Not nearly that dark and dashing figure with his dreadful eitheror. ( And what was that with random bed scene featuring him? It was way too creepywasn't his only love the Madame Guillotine, and his only interesthis job, and his only obsessionSir Percy?) Marguerite ... Prettiest woman in France? Cleverest woman in Europe? I think not. Although, whatever compelled her to break into the study of <sltn-Sir> <name> I haven't the faintest idea. And whatever my Lord Tony has done to deserve this death? Yes, every member of the League did pledge his life to <sltn-Sir> <name> , but <pro-he> would have never endangered any of them nor would have run away like a coward when <pro-his> dear friend faces mortal danger. And if by any means <pro-he> had to mourn <pro-his> companion, <pro-he> would have done that, mourn, not just move on as if nothing had happened. Which brings me to another point, <sltn-Sir> <name> . <pro-His> portrayal was most dreadful. <pro-He> was neither a lazy fop, nor a gallant and elusive hero who is a master of transformations. Nor did <pro-he> care too much about cravats ( <pro-his> pronunciation of that word alone made my ears bleed) And with <pro-his> own hands <pro-he> had never killed anyone. So what was that with <pro-him> randomly walking around and slaughtering people? The costumes were just too flashy for that time period as well. This is postrevolutionary France we are talking about! Not prerevolutionary. People in dresses like that stand out in a crowd quite easily. It was all just ... gah! Although, I must admit, after I watched other parts my opinion did change slightly. Watching it as a separate work, independent of Scarlet Pimpernel series, it was tolerable. Just your other average hero in the mask. But for what they tried to pass it, it is still miserable.

In [180]:
id = 2000
print(dmutant.groupby("type").get_group(SALUTATION).iloc[id]["original"])
print()
print(dmutant.groupby("type").get_group(SALUTATION).iloc[id]["template"])

It's hard to know exactly what to say about this ever so bland and dull little film. The story is predictable when not completely laughable. It's all a matter of " dutiful gestures " which, as presented here, carry absolutely no conviction. Yes, the MGM " production values " are gorgeous, and yes, Ms. Lamarr was exquisitely beautiful, but she and the great Spencer Tracy have absolutely no " chemistry " togetherand that's the only thing that would have made this parade of cliches at all effective ... It's my understanding that this movie received poor reviews when it was originally released; the passage of time has not improved it.

It's hard to know exactly what to say about this ever so bland and dull little film. The story is predictable when not completely laughable. It's <sltn-Ms.> <name> . Yes, the MGM " production values " are gorgeous, and yes, <sltn-Ms.> <name> was exquisitely beautiful, but <pro-she> and the great Spencer Tracy have absolutely no " chemistry " togetherand that's the only thing that would have made this parade of cliches at all effective ... It's my understanding that this movie received poor reviews when it was originally released; the passage of time has not improved it.

In [181]:
id = 2500
print(dmutant.groupby("type").get_group(SALUTATION).iloc[id]["original"])
print()
print(dmutant.groupby("type").get_group(SALUTATION).iloc[id]["template"])

Mr. Bean has shaped the face of British TV comedy. He has proved that you do not need wicked words or wit, a massive budget, a great deal of intelligence or even any intelligence to make something brilliant. And Mr. Bean is one of those characters who you just can't forget. Some of these episodes had me in stitchesyes, they're not realistic at all and they're all pretty stupid, but to be honest, realism is one of the barriers Bean has broken on its way to greatness. Rowan Atkinson and co. always manage to cook up interesting new ideasand hilarious new gagsremember when Mr. Bean drove his green Mini whilst sitting on a sofa on the roof? Mr. Bean is one of those things that never gets weakthe movie wasn't as good as this, but Bean has introduced a distinct new sense of humour to the world, and kids and adults alike will marvel at its immense fun factor. " Extras " and " Little Britain " can be damnedthis is British comedy at its best and most original. These escapades never get old! 10/10

<sltn-Mr.> <name> has shaped the face of British TV comedy. <pro-He> has proved that you do not need wicked words or wit, a massive budget, a great deal of intelligence or even any intelligence to make something brilliant. And <sltn-Mr.> <name> is one of those characters who you just can't forget. Some of these episodes had me in stitchesyes, they're not realistic at all and they're all pretty stupid, but to be honest, realism is one of the barriers <sltn-Mr.> <name> has broken on <sltn-Mr.> <name> way to greatness. Rowan Atkinson and co. always manage to cook up interesting new ideasand hilarious new gagsremember when <sltn-Mr.> <name> drove <pro-his> green Mini whilst sitting on a sofa on the roof? <sltn-Mr.> <name> is one of those things that never gets weakthe movie wasn't as good as this, but <sltn-Mr.> <name> has introduced a distinct new sense of humour to the world, and kids and adults alike will marvel at <sltn-Mr.> <name> immense fun factor. " Extras " and " Little Britain " can be damnedthis is British comedy at its best and most original. These escapades never get old! 10/10

In [177]:
id = 4000
print(dmutant.groupby("type").get_group(SALUTATION).iloc[id]["original"])
print()
print(dmutant.groupby("type").get_group(SALUTATION).iloc[id]["template"])

Mr. Moto's Gamble has a fairly straight forward plotwhen a boxer is murdered in the ring with a mysterious poison, it's up to the even more mysterious Mr. Moto to solve the case. I'm shocked at the number of positive reviews for Mr. Moto's Gamble on IMDb. Because to me ... well, I found it extremely disappointing. I enjoy Mr. Moto and I enjoy Charlie Chan, but I can't say I cared for this mishmash of the two. For those unfamiliar with the story behind Mr. Moto's Gamble, it was originally intended to be a Charlie Chan film. But when Warner Oland backedout, some of the scenes and action were rewritten for Peter Lorre and Mr. Moto. As I indicated, the end result left me underwhelmed. Mr. Moto is not Chan. He's more mysterious, he's more athletic, and he's more exotic. So trying to put Moto in a Chan film is like trying to fit a square peg into a round holeit doesn't work. And listening to Lorre/ Moto try to deliver one of Chan's trademark euphemisms just ends up sounding silly. Add to that the fact that almost 10 minutes of the already brief 72 minute runtime is made up of boxing scenes ( something that I never seem to enjoy) and you end up with a movie that I couldn't help but dislike. If I have to say something positive I would point to the performance of Keye Luke. But even he's not near enough to save Mr. Moto's Gamble in my eyes. Sorry, but a 4/10 is about the best I can give this one.

Mr. Moto's Gamble has a fairly straight forward plotwhen a boxer is murdered in the ring with a mysterious poison, it's up to the even more mysterious <sltn-Mr.> <name> to solve the case. I'm shocked at the number of positive reviews for the even more mysterious <sltn-Mr.> <name> 's Gamble on IMDb. Because to me ... well, I found it extremely disappointing. I enjoy the even more mysterious <sltn-Mr.> <name> and I enjoy Charlie Chan, but I can't say I cared for this mishmash of the two. For those unfamiliar with the story behind the even more mysterious <sltn-Mr.> <name> 's Gamble, it was originally intended to be a Charlie Chan film. But when Warner Oland backedout, some of the scenes and action were rewritten for Peter Lorre and Mr. Moto. As I indicated, the end result left me underwhelmed. the even more mysterious <sltn-Mr.> <name> is not Chan. <pro-He> 's more mysterious, <pro-he> 's more athletic, and <pro-he> 's more exotic. So trying to put the even more mysterious <sltn-Mr.> <name> in a Chan film is like trying to fit a square peg into a round holeit doesn't work. And listening to the even more mysterious <sltn-Mr.> <name> try to deliver one of Chan's trademark euphemisms just ends up sounding silly. Add to that the fact that almost 10 minutes of the already brief 72 minute runtime is made up of boxing scenes ( something that I never seem to enjoy) and you end up with a movie that I couldn't help but dislike. If I have to say something positive I would point to the performance of Keye Luke. But even he's not near enough to save the even more mysterious <sltn-Mr.> <name> 's Gamble in my eyes. Sorry, but a 4/10 is about the best I can give this one.

In [ ]:
id = 4000
print(dmutant.groupby("type").get_group(SALUTATION).iloc[id]["original"])
print()
print(dmutant.groupby("type").get_group(SALUTATION).iloc[id]["template"])

In [117]:
dmutant.groupby("type").get_group(GAW)

,label,mutant,template,original,identifier,type,gender,country,template_id
48,0,I'm sorry but I can't agree that this was a go...,I'm sorry but I can't agree that this was a go...,I'm sorry but I can't agree that this was a go...,boy,gaw,male,None,39
49,0,I'm sorry but I can't agree that this was a go...,I'm sorry but I can't agree that this was a go...,I'm sorry but I can't agree that this was a go...,brother,gaw,male,None,39
50,0,I'm sorry but I can't agree that this was a go...,I'm sorry but I can't agree that this was a go...,I'm sorry but I can't agree that this was a go...,daddy,gaw,male,None,39
51,0,I'm sorry but I can't agree that this was a go...,I'm sorry but I can't agree that this was a go...,I'm sorry but I can't agree that this was a go...,man,gaw,male,None,39
52,0,I'm sorry but I can't agree that this was a go...,I'm sorry but I can't agree that this was a go...,I'm sorry but I can't agree that this was a go...,father,gaw,male,None,39
...,...,...,...,...,...,...,...,...,...
793,1,L'Auberge Espagnole collected the audience whe...,L'Auberge Espagnole collected the audience whe...,L'Auberge Espagnole collected the audience whe...,aunt,gaw,female,None,48
794,1,L'Auberge Espagnole collected the audience whe...,L'Auberge Espagnole collected the audience whe...,L'Auberge Espagnole collected the audience whe...,girl,gaw,female,None,48
795,1,L'Auberge Espagnole collected the audience whe...,L'Auberge Espagnole collected the audience whe...,L'Auberge Espagnole collected the audience whe...,mom,gaw,female,None,48
796,1,L'Auberge Espagnole collected the audience whe...,L'Auberge Espagnole collected the audience whe...,L'Auberge Espagnole collected the audience whe...,lady,gaw,female,None,48
797,1,L'Auberge Espagnole collected the audience whe...,L'Auberge Espagnole collected the audience whe...,L'Auberge Espagnole collected the audience whe...,lady,gaw,female,None,48

In [118]:
id = 0
print(dmutant.groupby("type").get_group(GAW).iloc[id]["original"])
print()
print(dmutant.groupby("type").get_group(GAW).iloc[id]["template"])

I'm sorry but I can't agree that this was a good movie. Yes, it looked good visually, but it's the story that drives the movie and I must say the story sucked bigtime. How in the world did they manage to slip some of those plotholes past the critics. Better story and I would've gave it a higher vote but I was impossible to do that and still be able to live with myself. I have always been a fan of scary movies, and the previews really had me fooled. All the scary scenes were shown in the previews. And why did the family that got killed stay to haunt the house? Why did the father come back again? WHy did he decide to kill in the first place? Why were the kids the only ones to see the ghosts first? To many questions, not enough answers. If I could've gave it a zero, I would've.

I'm sorry but I can't agree that this was a good movie. Yes, it looked good visually, but it's the story that drives the movie and I must say the story sucked bigtime. How in the world did they manage to slip some of those plotholes past the critics. Better story and I would've gave it a higher vote but I was impossible to do that and still be able to live with myself. I have always been a fan of scary movies, and the previews really had me fooled. All the scary scenes were shown in the previews. And why did the family that got killed stay to haunt the house? Why did the <gaw> come back again? WHy did <pro-he> decide to kill in the first place? Why were the kids the only ones to see the ghosts first? To many questions, not enough answers. If I could've gave it a zero, I would've.

In [123]:
id = 1000
print(dmutant.groupby("type").get_group(GAW).iloc[id]["original"])
print()
print(dmutant.groupby("type").get_group(GAW).iloc[id]["template"])

IndexError: single positional indexer is out-of-bounds